### ISSUE TITLE
[Feature Request] Configuration to Allow Offset of Output Window

### ISSUE THREAD

**Issue by TillerBurr** [benlubas/molten-nvim#101]
While trying to integrate Molten into https://github.com/GCBallesteros/NotebookNavigator.nvim/pull/25, we have some odd placement of the output window, mainly because we are using `MoltenEvaluateRange` with an extended cell. See https://github.com/GCBallesteros/NotebookNavigator.nvim/pull/25#issuecomment-1848240254 for an example. This leads to the output window being displayed just below the `# %%` cell marker of the next cell. For those unfamiliar, this may look like the output is for the incorrect cell.

I've tried using `molten_virt_text_output` and `molten_virt_lines_off_by_1` in various states, but still have the same problem.

I guess what I'm asking is if you'd be interested in allowing the output to be shifted by some offset? I was messing around with Molten's code to get more familiar with nvim plugins and I have something that, in my limited testing, produces the desired output (from the fork https://github.com/TillerBurr/molten-nvim/tree/output-offset)

![image](https://github.com/benlubas/molten-nvim/assets/49296311/7702e617-c99a-43e9-b168-1ad1b4cbed1a)
![image](https://github.com/benlubas/molten-nvim/assets/49296311/69855934-1ab8-436b-9935-1d60452648e5)

I can open a pull request, but I wanted to create an issue beforehand, so it's not like I opened a pull request implementing a feature that hasn't been discussed.

**Comment by benlubas** [comment]
I'll take a look at your implementation. I don't have anything particularly against a way to offset windows, but I don't think that this is the best solution. If someone wanted to run a single line of code just to test it without running the whole cell, then the output window would cover the line of code they ran (similar if they wanted to just run code in a normal python file after using notebooknavigator, the last line of code would be covered).

A better solution might be discarding empty lines when figuring out where the molten cell ends. This could then show the window over the very last line of code in the cell.

**Comment by benlubas** [comment]
You implementation is fine, based on the variable name I don't think that it should effect virtual text output though.

But lmk what you think of solving this a different way

**Comment by TillerBurr** [comment]
That's fair. The same issue happens with virtual text, so I probably should have called it just `output_offset` or something similar.

As far as solving differently, I am completely open to that. The only issue with discarding empty lines is that the cell that is being defined actually ends on a cell marker (`# %%`), and so there are really no empty lines.

Is there a way to keep the output window open when the cursor is one line below a cell?

**Comment by benlubas** [comment]
> The only issue with discarding empty lines is that the cell that is being defined actually ends on a cell marker (# %%), and so there are really no empty lines

It should end on `# %%` at position 0, so the last "line" of the cell would just be an empty string. We just have to only consider the lines as defined by the boundaries of the cell.

> Is there a way to keep the output window open when the cursor is one line below a cell

no, output windows can only be open when the cursor is in the corresponding cell. This is both a limitation of the code from Magma, and also a behavior that I like, so changing it would be very hard and I don't really see a need in doing it.

**Comment by TillerBurr** [comment]
It turns out that it includes every thing on the line. This is the trimmed log version.

```
 molten.moltenbuffer:_show_selected:350 - span.get_text(self.nvim).splitlines()=[
    '# ruff: noqa: E501',
    '',
    'import re',
    'from itertools import product',
    '',
    '# %%'
    ]
```

The cell is defined as

```python
# %%
# ruff: noqa: E501

import re
from itertools import product

# %%
```

Without defining what a cell is, I don't know what to do. One option would be to create an optional config variable, e.g. `cell_marker` and then only modify the output window position if that option is defined. For example, if we define the cell marker to be `# %%`, then we would be able to ignore lines starting with the marker and iterate over the lines in reverse until we find the last empty cell and open the window/virtual text there. In the above example, the position would be the line above the second empty string. If we used the following code,

```python
# %%
import this




# %%
```

the output would show right below the `import this` line.

Thoughts?

**Comment by benlubas** [comment]
It's grabbing the whole line b/c that's what happens when column positions aren't passed.

https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/main/lua/notebook-navigator/repls.lua#L53

If notebook navigator passed column values as well, you can pass `0` for the ending column, and  then it shouldn't capture the `# %%`

Documented here: https://github.com/benlubas/molten-nvim#functions

I should update that documentation to better explain that it's 1 based indexing, and the behavior for passing out of bounds values.

**Comment by benlubas** [comment]
Correction, you should pass `1` for the ending col. I think passing 0 will give you the end of the line... like same as passing `-1` with 0 based indexing.

**Comment by benlubas** [comment]
Oh wait. I just went to write that documentation. There's a + 1 b/c I wanted to make to ending col inclusive... so `-1` for the ending column will be the end of the line. `0` for the starting col will be the end of the line. I really should change the way that works...

Adding it to the list of things to do in molten 2.0 I guess

**Comment by TillerBurr** [comment]
Thanks! I'll try and get something done sometime soon.
