### ISSUE TITLE
[Help] Questions regarding demo & overall usage experience

### ISSUE THREAD

**Issue by V3RGANz** [benlubas/molten-nvim#105]
Hello, I tried molten first time today. I have never had experience with notebooks in nvim before. First impressions are very good and promising.
However, I can't understand how can I do some basic things, which were demonstrated in the video attached to the readme.

- Currently my cell outputs are only shown when the cursor hovers chunk of code being executed. I don't want it to disappear after I move cursor away. How can I configure it this way?
- There is an options to execute line of code, and operator like `<MoltenEvaluateOperator>j20`, which is usable, but clearly not the smoothest workflow for cell execution. Is there an option to execute entire cell? I noticed that in demo it seems to be working this way.

**Comment by V3RGANz** [comment]
Also, plot renderings is a bit strange: very small and huge padding below.

![image](https://github.com/benlubas/molten-nvim/assets/14924440/22d65003-4277-4ec6-99c9-37a52a2cf354)

This is my configuration

```lua
local M = {
    "benlubas/molten-nvim",
    version = "^1.0.0",
    build = ":UpdateRemotePlugins",
    event = "VimEnter",
    init = function()
        -- this is an example, not a default. Please see the readme for more configuration options
        vim.g.molten_image_provider = "image.nvim"
        require("v3rganz.keymaps").molten_keymaps()
    end
}
```

```lua
local M = {
    "3rd/image.nvim",
    event = "BufRead",
    config = function ()
        require("image").setup {
            backend = "kitty",
            integrations = {
                markdown = {
                    enabled = true,
                    clear_in_insert_mode = false,
                    download_remote_images = true,
                    only_render_image_at_cursor = false,
                    filetypes = { "markdown", "vimwiki", "quarto" }, -- markdown extensions (ie. quarto) can go here
                },
            },
            max_width = 1024,
            max_height = 1024,
            max_width_window_percentage = math.huge,
            max_height_window_percentage = math.huge,
            window_overlap_clear_enabled = true,
            window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
        }
    end,
    dependencies = {
        -- need for image magick lua support
        {
            "theHamsta/nvim_rocks",
            event = "VeryLazy",
            build = env .. "pip3 install --user hererocks && python3 -mhererocks . -j2.1.0-beta3 -r3.0.0 && cp nvim_rocks.lua lua",
            config = function()
                require("nvim_rocks").ensure_installed({ "magick" })
            end
        }
    }
}
```

**Comment by benlubas** [comment]
> Currently my cell outputs are only shown when the cursor hovers chunk of code being executed. I don't want it to disappear after I move cursor away.

- There are two ways to see output, virtual text and the floating window. The floating window is the default, and it disappears when you move away, you can open it again by moving your cursor back over the code you ran and running `:MoltenShowOutput` or `:noautocmd MoltenEnterOutput`.
- Virtual text will stick around, but it can be buggy particularly with images and other output at the same time.  You can enable it with `vim.g.molten_virt_text_output = true`. 
    - If you keep your cells just showing images or just printing text the experience has been pretty seamless.
- When the virtual text is enabled floating windows don't show up by default, but you can still show/enter them with the same commands from above.

> Is there an option to execute entire cell

Yes! For the demo video I do have it working that way. There are two ways to get this behavior, the most reliable and best experience is with the `quarto-dev/quarto-nvim` plugin which has an integration with molten (that I wrote and will support if you have issues). This has the added benefit of giving you lsp auto completions, diagnostics and formatting in your code cells. It also gives you "run_all", "run_above", "run_below" etc etc.

The other option (which I also have configured for when I don't want to load quarto), is to use the `:MoltenEvaluateOperator` command in conjunction with a treesitter text object that selects the insides of a code block. I've written a little bit about how to do this in the quarto-nvim [wiki](https://github.com/quarto-dev/quarto-nvim/wiki/Integrating-with-Hydra#2-treesitter-text-objects). 

I plan to put all of this information in the [Notebook-Setup](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md) docs page at some point.

**Comment by benlubas** [comment]
> Also, plot renderings is a bit strange: very small and huge padding below.

This is probably a bug with the way I'm calculating the height of the output window. I can look into it. Going to make a separate issue tracking it.

**Comment by V3RGANz** [comment]
Thanks! This is exactly what I wanted.

P.S. I read docs prior to opening this issue, but seems that I was confused with `molten_virt_text_output` description in readme, because it was unclear that it will show outputs for all cells.

**Comment by benlubas** [comment]
added a sentence to the readme, thanks for pointing it out
