### ISSUE TITLE
[Bug] Image output disappears after modifying/switching buffer or creating any window 

### ISSUE THREAD

**Issue by V3RGANz** [benlubas/molten-nvim#109]
- OS: macOS 12.4
- NeoVim Version: 0.9.4
- Python Version: 3.11.4
- Python is installed with: native or brew
- Health checks
```
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- WARNING Optional python module cairosvg not found
  - ADVICE:
    - pip install cairosvg
- OK Python module pnglatex found
- OK Python module plotly found
- OK Python module kaleido found
- OK Python module pyperclip found
- OK Python module nbformat found
```

## Description
If cell has image output, it disappears (for all such cells) after any of these actions:
- buffer modified (not only inside cell).
- switched to other buffer and 
- lsp-hover is called or any window created (like `:h`)

`MoltenEnterOutput` still shows correct output with image

## Reproduction Steps

https://github.com/benlubas/molten-nvim/assets/14924440/f4a39f9b-7e4b-433c-a7ec-6a3317f14c0e

1. Create cell with image output
2. Evaluate cell
3. Modify buffer / call lsp-hover / switch buffer
4. Images disappear

## Expected Behavior
Image outputs remain.

**Comment by benlubas** [comment]
I'm not seeing that the images disappear after editing the buffer, I just see that they don't update their position (discussed in #50).

When leaving a window, I see that the images disappear and don't come back. I'll look into that. If I had to guess there's something wrong with the buf leave auto command

**Comment by benlubas** [comment]
I am thoroughly stumped on this one. I want to blame image.nvim, but I can't reproduce this issue without molten. 

The reason I want to blame image.nvim is I'm never calling the image.clear method when creating a new window. this is easy to confirm with print statements b/c all of image nvim interface is in one file, in a couple of functions.

But then when I go to try and recreate this as a simple image.nvim example, I can't. It doesn't happen with the document integration.

**Comment by V3RGANz** [comment]
I also sometimes face issue when image not rendered just after cell code was evaluated, without switching buffer or window. But I couldn't find clear way to reproduce it (just happens from time to time), so didn't mention this in the issue. But maybe this information will help somehow. And this is always issue of virtual text. Floating window always show correct output in my case.

**Comment by V3RGANz** [comment]
> The reason I want to blame image.nvim is I'm never calling the image.clear method when creating a new window. this is easy to confirm with print statements b/c all of image nvim interface is in one file, in a couple of functions

This is kind of interesting. I've tested it the same way, `image_api.clear` is called anytime current buffer is leaved. Including creating window like lsp-hover. So the problem shouldn't be in image.nvim

update: but clear not called when `:noautocmd MoltenEnter` is called, so it must be autocmd

**Comment by benlubas** [comment]
Sorry I should have mentioned. I commented out these calls b/c they looked to be the problem. But I was still having issues even after doing that.

https://github.com/benlubas/molten-nvim/blob/1a788b9e3bcba4b33e64064e406bf8f750a7f15a/rplugin/python3/molten/__init__.py#L128-L130

Notably, commenting these out fixes the problem for me when I'm simply switching windows. But when I create a new split window, the issue still happens. doesn't matter how I create the split (<C-w>v/s, `:h help`, telescope), it always causes the images to disappear.

**Comment by V3RGANz** [comment]
I think I figured out what happening. The problem that notebook is markdown file (or `.qmd` which I also enabled in image.nvim).
This is because markdown integration enabled, and this line is executed for notebook images:
https://github.com/3rd/image.nvim/blob/master/lua/image/utils/document.lua#L72

For regular markdown, images same idx were added to rendering queue to be re-rendered correctly:
https://github.com/3rd/image.nvim/blob/master/lua/image/utils/document.lua#L65

However, this is not true for images which are loaded externally, not with markdown syntax and they not appear as in our case.

When I set `enable=false` for markdown integration in image.nvim images not clear after creating split etc.

**Comment by benlubas** [comment]
Great find!

**Comment by V3RGANz** [comment]
> I also sometimes face issue when image not rendered just after cell code was evaluated, without switching buffer or window. But I couldn't find clear way to reproduce it (just happens from time to time), so didn't mention this in the issue.

I also figured out why this happened. I had "noice" notification plugin, and image.nvim considered them as overlapping windows (visually they not overlapped, but maybe technically yes) and stop rendering after. Luckily, including "noice" to `window_overlap_clear_ft_ignore` in nvim configuration helps.

> I commented out these calls b/c they looked to be the problem. But I was still having issues even after doing that.

This should be disabled at least as an configurable option I think, at least I commented it so far :), clearing on split or lsp-hover may be not desired

**Comment by benlubas** [comment]
Yup, I'm going to remove those lines, they're definitely just left over from a time when everything was floating windows and it didn't make sense to keep things open when leaving the window.

The noice windows thing is interesting I didn't consider that, I do know that there's an issue with the way "overlapping" is defined, currently it's a really naive implementation, which basically means it clears all images if there's any floating window open.

**Comment by benlubas** [comment]
@V3RGANz  this should be all cleared up now, if you use the main branch of both image.nvim and molten-nvim.

If it works for you, you can close the issue, if it doesn't lmk what's still causing trouble

**Comment by V3RGANz** [comment]
Thanks!
