### ISSUE TITLE
[Bug] Images are placed above virtual text in virt text output after they're imported

### ISSUE THREAD

**Issue by benlubas** [benlubas/molten-nvim#117]
## Description

When importing images (either from a ipynb or from the magma output format) images seem to be placed above the heading virtual text after scrolling past the output. This results in the text showing up at the bottom of the output, and the image also shos up at the bottom b/c images will just always assume they're the last thing on the line, that's an image.nvim bug that I should fix one day, but whatever.

## Reproduction Steps

Produce an image output, and save it `:MoltenSave`. Make sure you're using virtual text outputs.

Deinit, then `:MoltenLoad`. Image shows up like this:

<img width="697" alt="image" src="https://github.com/benlubas/molten-nvim/assets/56943754/7c425b58-4aa7-49c4-968e-8fccaa8d3756">

## Expected Behavior

It should render like this (and it does until I scroll past it for some reason):

<img width="697" alt="image" src="https://github.com/benlubas/molten-nvim/assets/56943754/dd25f5a5-9c11-4f51-893f-9f9bc2d81250">

I think that molten isn't recognizing the virtual text as rendered or done, and it's getting re-rendered somehow, which places it after the image

**Comment by V3RGANz** [comment]
I am experiencing this issue without any save/load on my second machine (on my first machine everything work as intended). I evaluate cell and it shows blank lines, image, and text intended to be at the top is actually at the bottom overlapping the image.
It also fixes after I open floating window with `:MoltenEnter` and close it.

P.S.
When I "fix" appearance with `:MoltenEnter` and then reevaluate cell couple of times, molten seems to not recognise image as cell output and appends new image without clearing old (pic below). However, I think everything is related to the same bug and might be outside of save/load mechanics.

<img width="344" alt="image" src="https://github.com/benlubas/molten-nvim/assets/14924440/f73fd0fb-e6d9-42df-bfe5-a7c600afc793">

<img width="354" alt="image" src="https://github.com/benlubas/molten-nvim/assets/14924440/c49ed737-4d7f-4d15-88a4-ff997d07edc5">

**Comment by benlubas** [comment]
I did find the problem with way we were loading images that was causing this issue. 

I wouldn't be surprised if there are other issues tho. 

Image nvim just shipped an update that broke some things as well. I have a fix for both issues that I'm aware of but still on a train I'll keep this issue open and at you when both are merged hopefully later tonight (in 3 ish hours)

**Comment by benlubas** [comment]
I'll mention that the first issue of text overlapping the image is an image.nvim issue. The image doesn't always display over its extmark when there are multiple extmarks that take up space on the same line.

I have tried to fix this issue but it's very weird and always feels like a neovim bug, or my implementation breaks some other part of the image nvim plugin lol. 

The issue of images hanging around might be a molten problem tho.

**Comment by benlubas** [comment]
@V3RGANz both image.nvim and this have been merged. You can try with latest version of both and hopefully the problem is fixed. if it's now I can take a look maybe later today or tomorrow.

**Comment by benlubas** [comment]
Going to close for now, feel free to re-open or create a new issue if you still encounter this
