### ISSUE TITLE
[Feature Request] Variable Explorer

### ISSUE THREAD

**Issue by benlubas** [benlubas/molten-nvim#13]
It would be great to have a variable explorer in Molten. This could help users see what code they've already run, and have access to the state of their code.

One of the main downfalls (in my opinion) of notebook style programming is that you can write some code that takes an already defined variable and modifies it. But if you run that block more than once without realizing, you've now fudged your variable state and all your numbers from then on out are incorrect until you rerun your notebook.

Having a variable explorer open would fix this issue.

## implementation

If this plugin only supported python, this could be as simple as running the `%whos` IPython magic command to get the variable state whenever the use runs code. However. This is just something IPython implements, and is not a general feature of the Jupyter Kernel. As such, other kernels do not how this implemented, and we can't rely on it.

Jupyter client apparently implements an [inspect-variables](https://jupyter-client.readthedocs.io/en/stable/messaging.html#inspectvariables) command (?) that should give us variable information as well. I'd imagine this is supported by a wider range of jupyter clients (though I'd be surprised if all of them supported it).

**Comment by 5183nischal** [comment]
I have just started playing with Molten and it's amazing -- thank you! I wanted to request something similar. A  fuzzy searchable variable explorer using telescope maybe? Maybe this [plugin](https://github.com/lkhphuc/jupyter-kernel.nvim) will be useful to see how this might be implemented?

**Comment by benlubas** [comment]
I'm pretty sure that the plugin you linked could work at the same time as Molten. If you start the kernel with `:MoltenInit`, and then attach to it with the `:JupyterAttach`  command from the other plugin, things should work, though I haven't tested. Oh but it doesn't have search functionality built in I don't think.

I'll take a look at the other plugin when I get around to implementing this, hopefully it uses the same method of fetching variable information that I plan to use so I have an example to work off.
