### ISSUE TITLE
[Help] How to access output buffer as shown in the example

### ISSUE THREAD

**Issue by ayghri** [benlubas/molten-nvim#141]
How to access output buffer as shown in the example so that I can copy text from the output?

Your tutorial video seems to be using `<localleader>o`, but the command is not listed.

Thanks

**Comment by benlubas** [comment]
The all the commands for interacting with the plugin are listed in the readme. You can use `:MoltenEnterOutput` to show the floating window if it's not open and enter the floating window when it is open.
