### ISSUE TITLE
[Help] How do i render Latex?

### ISSUE THREAD

**Issue by Flaviongas** [benlubas/molten-nvim#143]
Everything is installed correctly, i can run code just fine with Python, R and Julia. But i don't know how to render Latex.

Do i have to put inside ``` ```? It seems to think that is python code.

**Comment by benlubas** [comment]
You have to get the kernel to return a `text/latex` mimetype for the plugin to render latex. The easiest way to render latex that you type is with ipython's latex [cell magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-latex).

So you run the following "code" with the iptyhon kernel:

```latex
%%latex

this is latex, here is some math: $ \frac{1 + 3}{3 + 5} = 0.5 $
```

You should see an image of the rendered latex

**Comment by Flaviongas** [comment]
Thank you!!!
