### ISSUE TITLE
[Help] MoltenInit interaction with LazyVim

### ISSUE THREAD

**Issue by jorgesca** [benlubas/molten-nvim#144]
I post this as help because I don't think this is a bug, rather an unwanted interaction that I don't understand. I am in the process of setting up molten, with the final intention of interacting with jupyter notebooks from within neovim (not quite there yet). I also happen to base my config off LazyVim, and I noticed that when running MolteInit without arguments, neovim doesn't display anything. I tried without LazyVim and MoltenInit works as it should, i.e. lists the available kernels and ask for selecting an option.
Do you know what could be causing LazyVim to not display the options? I know you probably don't use LazyVim, so in that case, what is the mechanism Molten is using to display the list of kernels and ask for a selection? Maybe knowing that I can find the information I need to fix this.
Thanks for your work, it would be very nice to not have to use the browser with notebooks anymnore.

**Comment by benlubas** [comment]
If you run the `:UpdateRemotePlugins` command manually, what happens?

I think that lazy vim makes it really easy to accidentally disable remote plugins, which obviously breaks this remote plugin.

**Comment by jorgesca** [comment]
Maybe I wasn't clear enough. Molten IS working, I can attach a kernel typing 
`:MoltenInit ipykernel`
(previously I did MoltenInfo to find out what were the available kernels)
The problem Is that I can't see the list, so I can't select an option (well, I can, but blindly)

**Comment by benlubas** [comment]
Oh, then it's probably an issue with whatever is handling `vim.ui.select()`.

Do you use any plugins like `noice.nvim` or `dressing.nvim` that alter the UI?

**Comment by jorgesca** [comment]
This is the init.lua I used to verify that moltenm works OK when not using LazyVim:

```local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
    	"benlubas/molten-nvim",
	version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
	build = ":UpdateRemotePlugins",
	init = function()
		-- this is an example, not a default. Please see the readme for more configuration options
		vim.g.molten_output_win_max_height = 12
	end,
    }
})
```

**Comment by jorgesca** [comment]
> Oh, then it's probably an issue with whatever is handling `vim.ui.select()`.
> 
> Do you use any plugins like `noice.nvim` or `dressing.nvim` that alter the UI?

I believe LazyVim uses at least noice.nvim

So it's `vim.ui.select` that molten uses? Maybe I can search a bit more in that direction. Maybe I have some option so molten's output is correctly displayed

**Comment by benlubas** [comment]
Could you send a screen shot or video of the problem?

**Comment by jorgesca** [comment]
OK, I'll come back with a video

**Comment by jorgesca** [comment]
![molten_lazyvim](https://github.com/benlubas/molten-nvim/assets/956679/70275efe-e0fe-4e44-91ff-368ecccec89c)

**Comment by benlubas** [comment]
Oh yeah, that's `noice.nvim` messing with things..

Let me see what happens for me.

**Comment by benlubas** [comment]
I see this:

![image](https://github.com/benlubas/molten-nvim/assets/56943754/b9b0a6d8-3f1d-453d-b461-dd8085be06e3)

[Here](https://github.com/benlubas/.dotfiles/blob/main/nvim/lua/plugins/noice.lua) is my noice config if that will help you. I don't use noice normally, I just keep this config around to experiment with.

So I'm not supper familiar with configuring the plugin. If you share your config I might be able to help. but no promises

**Comment by jorgesca** [comment]
Thanks, and don't worry. 

> [Here](https://github.com/benlubas/.dotfiles/blob/main/nvim/lua/plugins/noice.lua?rgh-link-date=2024-02-10T18%3A11%3A03Z) is my noice config if that will help you. I don't use noice normally, I just keep this config around to experiment with.
> 
> So I'm not supper familiar with configuring the plugin. If you share your config I might be able to help. but no promises

Thanks, I see the same if I replace LazyVim's config with yours, so I know now that there's a config issue. I'll try to dig into Noice's docs, and understand the differences between both configs. You've been very helpful, I really appreciate it. I'll close this for now.
