### ISSUE TITLE
[Feature Request] Alternate Image/Plot Output

### ISSUE THREAD

**Issue by akthe-at** [benlubas/molten-nvim#149]
This is a continuation of a conversation that began on twitch today. I was wondering if there was a way to get an alternate image output for those of us that can't use image.nvim on Windows. I mentioned that nvim-r has a window popup outside of neovim with the plot as an alternate. You asked me to open an issue here :)

**Comment by benlubas** [comment]
@akthe-at checkout #150 and let me know how that works for you. It seems to work on linux for me. I haven't tested on mac or windows yet.

**Comment by akthe-at** [comment]
I'm trying to test but I'm having an epic fail it seems. I last uninstalled molten a month or so ago after realizing images wasn't going to work on Windows. Now I just reinstalled it and everything seems kosher until I try to bring in an .ipynb file. So since I can't get past this yet, I am not much of a beta tester yet.

![image](https://github.com/benlubas/molten-nvim/assets/105152139/239ac678-bc6e-4168-a440-b74ecd62f022)

**Comment by akthe-at** [comment]
ps. Molten is working just fine in regular .py files with executing and viewing code.

**Comment by benlubas** [comment]
Oh yeah, Molten doesn't convert ipynb files. I use the jupytext.nvim plugin for that (which requires the jupytext command line tool). 

More details in the [notebooks setup docs](https://github.com/benlubas/molten-nvim/blob/main/docs%2FNotebook-Setup.md) in the notebook conversion section. 

If the popup images are working for you in a python file tho, I'm confident it will work in the converted ipynb file after you get that setup.

**Comment by akthe-at** [comment]
Sorry, I messed up my understanding of that workflow. I understand that and got the conversion of the notebook down correctly now. However, I mislead you. There were no pop ups happening in the regular .py files and there aren't any popups in the converted notebook to markdown file now.

Actually, the :MoltenImagePopup command isnt showing up in the command menu either despite seeming like I am on the correct branch (I know it did a rebuild because I had to redo the windows hack with the \\\\ path items.

![image](https://github.com/benlubas/molten-nvim/assets/105152139/d78b62e9-bb66-4ccb-be90-12d2f51f884d)
![image](https://github.com/benlubas/molten-nvim/assets/105152139/530390c3-128f-4ca4-be9d-aa7577b4fbd0)

**Comment by benlubas** [comment]
Oh damn. You're on Windows I forgot about that. Normally you'd run `:UpdateRemotePlugins` but that is broken on Windows, so I need to get you an up to date manifest file. Currently don't have Wi-Fi bc I'm traveling, typing this on my phone.

You can modify the manifest file and add the command yourself if you want. It's fairly manageable. It's a new command called `MoltenImagePopup` and it's synchronous with no args and no bang. 

The manifest file is the same one mentioned in the windows doc page.

**Comment by akthe-at** [comment]
I fixed up the manifest and now I see the option but here is the error :\ 
![image](https://github.com/benlubas/molten-nvim/assets/105152139/a3538517-e73e-415b-b909-21d2f6e67d41)

**Comment by benlubas** [comment]
Okay. I will give you a proper manifest tomorrow morning.

**Comment by benlubas** [comment]
Here you go, don't forget to change that file path following the [windows](https://github.com/benlubas/molten-nvim/blob/main/docs/Windows.md) docs

```vim
call remote#host#RegisterPlugin('python3', '/Users/benlubas/github/molten-nvim/rplugin/python3/molten', [
      \ {'sync': v:true, 'name': 'MoltenDeinit', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenDelete', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEnterOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenReevaluateCell', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateLine', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateOperator', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateVisual', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenExportOutput', 'type': 'command', 'opts': {'bang': '', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenGoto', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenHideOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenImagePopup', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenImportOutput', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenInfo', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenInit', 'type': 'command', 'opts': {'complete': 'file', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenInterrupt', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenLoad', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenNext', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenOpenInBrowser', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenPrev', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenReevaluateAll', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenRestart', 'type': 'command', 'opts': {'bang': '', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenSave', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenShowOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateArgument', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateRange', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenAvailableKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenBufLeave', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenRunningKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenDefineCell', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOperatorfunc', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'MoltenSendStdin', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'MoltenTick', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'MoltenTickInput', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnBufferUnload', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnCursorMoved', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnExitPre', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnWinScrolled', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenStatusLineInit', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenStatusLineKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'MoltenUpdateInterface', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenUpdateOption', 'type': 'function', 'opts': {}},
     \ ])
```

**Comment by akthe-at** [comment]
Same error even with the new manifesto,

![image](https://github.com/benlubas/molten-nvim/assets/105152139/a0660d43-f024-4f29-b5ca-e2a4c509ea9d)

**Comment by benlubas** [comment]
Hmmm. I can't replicate that. I did find a bug though, when the image provider isn't set, the command doesn't work (but I'm not seeing an error, it just fails silently), which kinda defeats the purpose of this feature. So I will fix that, but I can't test on windows until I'm back home. And then I probably won't have time for a little bit.

Could you also test the `:MoltenOpenInBrowser` command? that command and this one are structured the exact same way.

**Comment by benlubas** [comment]
You can try with the latest (same manifest should work) but I suspect that this still won't work b/c it seems like you're getting a different error. I will have a look on my windows machine when I'm back home and have some time (which might not be until thursday or friday.

**Comment by akthe-at** [comment]
Good and bad news...I will start with the bad.

![image](https://github.com/benlubas/molten-nvim/assets/105152139/0f4cf7ae-7928-4239-a3b1-2fc2968a0574)

But on my second monitor up popped my plot! I had to do plt.show() on my matplotlib plot to showup though. Actually...as I am typing this I went and got rid of plt.show() and the plot showed up the second time and no error occured...

MoltenOpenInBrowser did not error btw but told me it had no html to output.

**Comment by benlubas** [comment]
Nice. I think the error you have now seems like it's fixable. I should just return early instead of asserting.

Pretty sure that that's an error caused by the function being async which wasn't accounted for when the code was written. 

I can fix it tomorrow evening.

It is weird that I've never gotten it before tho. Probably some inconsistency with windows or maybe performance based.

**Comment by benlubas** [comment]
@akthe-at sorry for the delay, I just pushed a change (to the `feat/image_popup` branch) that I think will fix that error. Hopefully it doesn't break anything else. If other features of the plugin aren't working for you, then I might have to make one of the functions synchronous or something.

I'm unable to test b/c I don't have that error in the first place.
