### ISSUE TITLE
[Feature Request] Allow Wezterm to be an image provider

### ISSUE THREAD

**Issue by akthe-at** [benlubas/molten-nvim#154]
Please include:
 - I wonder how you would feel about adding "Wezterm" as an image provider. I feel like on windows there may be something here that you could add that would allow wezterm to open a temporary split, display the image output, then close on the next key press. or not (depends on how to setup the command.
- I got the idea from the M.PreviewImage via [image_preview.nvim](https://github.com/adelarsq/image_preview.nvim/blob/main/lua/image_preview/init.lua)
- Initial testing from my windows based neovim setup looks promising. 
- I think this might be something I could work on contributing but I don't know if there is a temporary image path that is created by the image output cells that would work with wezterm's imgcat command. Please see my images below.

![image](https://github.com/benlubas/molten-nvim/assets/105152139/0b75a04a-f396-4507-8db4-cd145247cb15)

![image](https://github.com/benlubas/molten-nvim/assets/105152139/9347d560-44e8-4119-8103-6c9155aca291)

**Comment by benlubas** [comment]
Westerm supports kitty graphics protocol (although it's a little janky). But is that not better than what you're asking for?

**Comment by akthe-at** [comment]
I believe it supports Kitty and iterm2 protocols but I can not for the life of me get image.nvim to work on windows...even after succesfully getting all of the dependencies hacked together.  The underlying hologram.nvim seems to cause the failure on Windows.

**Comment by akthe-at** [comment]
> Please include:
> 
> * I wonder how you would feel about adding "Wezterm" as an image provider. I feel like on windows there may be something here that you could add that would allow wezterm to open a temporary split, display the image output, then close on the next key press. or not (depends on how to setup the command.
> * I got the idea from the M.PreviewImage via [image_preview.nvim](https://github.com/adelarsq/image_preview.nvim/blob/main/lua/image_preview/init.lua)
> * Initial testing from my windows based neovim setup looks promising.
> * I think this might be something I could work on contributing but I don't know if there is a temporary image path that is created by the image output cells that would work with wezterm's imgcat command. Please see my images below.
> 
> ![image](https://private-user-images.githubusercontent.com/105152139/309153398-0b75a04a-f396-4507-8db4-cd145247cb15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTU0NzgsIm5iZiI6MTcwOTI5NTE3OCwicGF0aCI6Ii8xMDUxNTIxMzkvMzA5MTUzMzk4LTBiNzVhMDRhLWYzOTYtNDUwNy04ZGI0LWNkMTQ1MjQ3Y2IxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjEyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzAyNmIzZTU1MzZhZjE4YjQ4YTY2MDMwYjIwYzliYmE3YTE2ZmQzNDQxMjM5NzEzMzlhMzMxZDk0YTcyNjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IM8p6PUcvNlv-OZ5Em1wCvAaPIzc5LbtrH8861cXFxE)
> 
> ![image](https://private-user-images.githubusercontent.com/105152139/309153498-9347d560-44e8-4119-8103-6c9155aca291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTU0NzgsIm5iZiI6MTcwOTI5NTE3OCwicGF0aCI6Ii8xMDUxNTIxMzkvMzA5MTUzNDk4LTkzNDdkNTYwLTQ0ZTgtNDExOS04MTAzLTZjOTE1NWFjYTI5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjEyNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzFhMWI3MDcxMTBjMDg0MGJhNDU1MzJiZTdkZDU5MjY0ZWRjMjU2YTIxNWZjNmU1ODhkODFlMTZiYTAyNzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0uUIJusbKhW5mrwyfvtwr1--FOsYZ7IjchiFiyIVi6Q)

the cli command for imgcat on wezterm has a --hold flag that can be used to replace pause vs read

**Comment by benlubas** [comment]
Hologram.nvim isn't used. Image.nvim is, make sure you're using that

Although. I vaguely remember image nvim not supporting windows..

**Comment by akthe-at** [comment]
I tried both, they both had the same error related to ioctl so I thought maybe image.nvim was using hologram.nvim's api or something but I definitely tried them both separately. You are correct about them saying on their github that they don't support Windows but I didn't know of any other way to try and get molten to use the kitty protocol to display an image inside the terminal.

**Comment by benlubas** [comment]
Yeah i don't think rendering kitty graphics on windows is possible (by default). I remember reading through this thread a while ago: https://github.com/wez/wezterm/issues/1673#issuecomment-1054311400

There is a workaround available if you're willing to setup a graphical WSL environment and then use kitty through that. Detailed here: https://github.com/kovidgoyal/kitty/discussions/7054

Currently that workaround and then `:MoltenImagePopup` are the only known working ways for molten to display images on Windows I think.

A Wezterm backend the way you suggest would probably be possible. You can just implement a separate Canvas for it in the `images.py` file. Might require some trickery, I would be happy to answer questions if you want to implement it

**Comment by lazymaniac** [comment]
https://github.com/jstkdng/ueberzugpp/issues/165 
On windows image.nvim should work with ueberzug backend and wezterm

**Comment by benlubas** [comment]
Oh sweet I didn't know that. I can add a note to the windows doc about this stuff.. @lazymaniac does that work in normal windows? That post seems to be talking about WSL

**Comment by akthe-at** [comment]
Is it windows or windows via WSL? I'll test tonight!


On Mar 2, 2024 9:09 AM, Ben Lubas ***@***.***> wrote:

Oh sweet I didn't know that. I can add a note to the windows doc about this stuff.

**Comment by lazymaniac** [comment]
> Oh sweet I didn't know that. I can add a note to the windows doc about this stuff.. @lazymaniac does that work in normal windows? That post seems to be talking about WSL

Yes, ueberzug works in linux so it requires WSL2. Sorry I forgot to mention this

**Comment by akthe-at** [comment]
Ben, I think this is something that I would like to try and implement and I've been reading through the codebase over the last couple of days. I think this has the potential to be a nice addition for those of us on Windows without WSL. 

I am wondering about the route of the new Canvas extension vs making it implemented more like the external image pop-up. Would I just pass on a lot of the methods related to updating and dismissing the currently implemented image canvas? The proposed idea would result in a split window pop-up that would hold the graphic until the next key press and would not persist in the file. I would also need to think about how to handle somebody running all or multiple cells that have graphics in each.

**Comment by benlubas** [comment]
I would prefer a canvas implementation for something like this. I see this as an alternative to image.nvim rather than something extra.

---

Instead of the graphic disappearing after key press you might find it more useful and usable if the split window persisted until the next image needed to be displayed and then it can just draw the next image in the same split.

Depending on how performant wezterm's image drawing is, you could even keep old images in the split window (maybe include their execution count right above/below it so people know where each image came from).

I'm happy to help answer questions about the code base if you have any. But I won't be much help with wezterm's protocols unfortunately.

**Comment by akthe-at** [comment]
So I've been starting work on this but I wanted to try and see if I could use a debugger to watch the flow of data through the plugin... Have you ever been able to do such a thing? I have no idea if you can actually debug a new event plugin that is half in Lua half in python that runs python code in a python script.

**Comment by benlubas** [comment]
yeah I've never been able to debug this. I've also never tried. I just print statement debug with `nvim.out_write(f"{var}\n")`

**Comment by akthe-at** [comment]
So I've got a simple working example implemented. However, it's currently only set up for when you have the image_prov == "wezterm" and auto image pop-up is set to true.

I'm doing more research on the ability to send repeated commands to wezterm and keeping the split persistent. I'm struggling with moving back and forth between the neovim window and the wezterm split.

**Comment by benlubas** [comment]
> and auto image pop-up is set to true.

Could you remove that requirement? I don't want to have that configuration variable doing more than one thing.

> I'm struggling with moving back and forth between the neovim window and the wezterm split.

Are you trying to make the movements automatic so the user doesn't get 'tabbed' out of their neovim? I agree that's probably an important part of the UX here.

If it's too much to get that working, and you're okay with it, I'd be okay accepting the change without that automatic tab switching.

**Comment by akthe-at** [comment]
> > and auto image pop-up is set to true.
> 
> Could you remove that requirement? I don't want to have that configuration variable doing more than one thing.

Certainly! I've already moved away from this and working on putting it into the other image rendering pathway but now I need to figure out how to avoid my now new image render infinity loop. A new split is being created each time the canvas is checked for updates.

> 
> > I'm struggling with moving back and forth between the neovim window and the wezterm split.
> 
> Are you trying to make the movements automatic so the user doesn't get 'tabbed' out of their neovim? I agree that's probably an important part of the UX here.

I am definitely trying to avoid the user being tabbed out of their neovim window. I think its possible to do but could require a lot of extra code ala some of the wezterm.lua code from https://github.com/willothy/wezterm.nvim. But I don't think we want to add another external dependency like image.nvim for this so it would need to be written.


> If it's too much to get that working, and you're okay with it, I'd be okay accepting the change without that automatic tab switching.

Do you mean you would rather have the version where the image/pane are not persisted? The two routes I see are:

A - Per line/cell image view. Not persistent. Each time code is run that has image output it would open a new wezterm terminal split, renders the image, then waits to dismiss via the next keypress by the user. Does not tab out the user from their neovim window.

B - Persistent terminal split that continuously gets new images sent to it and rendered. May also include cell output identification information above or below the rendered image. Just need to figure out the correct implementation to keep the users cursor inside neovim.

Regardless of these two paths I feel like I could also implement a setting that takes a table of options to select if they want horizontal vs vertical split, and the option to set a default size for the split if they want to set it or to allow wezterm wezterms default size.

**Comment by benlubas** [comment]
I'm fine with whatever behavior can get working, though I'd prefer the "stays open and you don't get tabbed out" if you can get it to work. If you want to make wezterm.nvim an optional dependency I don't have a problem with that.

Making it all configurable would be great as well!

**Comment by akthe-at** [comment]
> I'm fine with whatever behavior can get working, though I'd prefer the "stays open and you don't get tabbed out" if you can get it to work. If you want to make wezterm.nvim an optional dependency I don't have a problem with that.
> 
> Making it all configurable would be great as well!

I have got a working version implemented [on my fork](https://github.com/akthe-at/molten-nvim/tree/wez_dev) but who knows how "good" my implementation is. This might be a bit hacky. I have one big of chunk of things that I want to finish but I wasn't sure how I should go about getting plugin "options" to the new canvas subclass. So my major items to finish in my mind are this. 

- [ ] Let user defined plugin options pass to the canvas which will control how the terminal split is created/positioned
- [ ] Finish Typing/Comments
- [ ] Finish input validation/error handling
- [ ] Add Cell output identification echo under or above graphic in terminal
- [ ] Add to project readme/documentation

**Comment by benlubas** [comment]
@akthe-at  could you open up a draft PR so it's easy to see the diff and comment on the code there?
