### ISSUE TITLE
[Help] How do I create a new cell?

### ISSUE THREAD

**Issue by Fustigate8933** [benlubas/molten-nvim#160]
I want to create a new cell with a keybind in jupyter notebooks, I have tried to manually type out the "```python```", but that's pretty tedious. I do have to set my own macro, or is there already one builtin Molten?

**Comment by benlubas** [comment]
Create a keybind or snippet for it.

I have a luasnip snippet that looks like this:

```lua
ls.add_snippets("markdown", {
  -- code cell
  s(
    {
      trig = "^%s*`",
      trigEngine = "pattern",
    },
    fmta(
      [[```<lang>
<last>
``]],
      {
        lang = c(1, { t("python"), t("lua"), t("") }),
        last = i(0),
      }
    )
  ),
})
```

If you're unsure about how to set that up, I can elaborate more on it.

---

You could also add a keybind like:
```lua
vim.keymap.set("i", "<localleader>cell", "```python\n\n```<up>")
```

Placing that keymap in an ftplugin and making it buffer local will prevent you from triggering it outside of a markdown file for example.

As a full example of that, your `nvim/ftplugin/markdown.lua` file would contain:
```lua
vim.keymap.set("i", "<localleader>cell", "```python\n\n```<up>", { buffer = true })
```

**Comment by Fustigate8933** [comment]
Ah, that worked perfectly!!! Thank you so much!
