### ISSUE TITLE
[Help] How do I wrap text in output?

### ISSUE THREAD

**Issue by Fustigate8933** [benlubas/molten-nvim#161]
![image](https://github.com/benlubas/molten-nvim/assets/55949973/60083dbb-9ef4-48e4-a9c2-d60b73353517)

As above in the image, in output of code using molten + quarto, the first line of text was too long and was cut off at the right side. Normally in insert mode my text wraps properly, since I have set wrap inside nvim settings. How do I also enable wrapping for molten outputs? Thanks! (it's an .ipynb file btw)

**Comment by benlubas** [comment]
There's an option in the readme
