### ISSUE TITLE
[Bug] Hydra conflicts with MoltenUpdateInterface running async

### ISSUE THREAD

**Issue by sadguitarius** [benlubas/molten-nvim#165]
I'm using Molten with a relatively vanilla setup using mostly the guides found here and Hydra integration from [this page](https://github.com/quarto-dev/quarto-nvim/wiki/Integrating-with-Hydra). When I execute a cell in a Quarto document from the Hydra window, the first time works fine, but running the cell a second time results in a massive error message. Strangely, subsequent cell executions do work fine. This only happens from the Hydra window and not when running the QuartoSend command on its own, so it seems like Hydra is blocking something. 

I followed the Python trace and found that by making MoltenUpdateInterface run synchronously, I don't experience the issue. This could be related to #145 somehow. Would you be ok with going ahead and making this a sync function? I guess the alternative would be to address the issue with Hydra, but as it doesn't sound like there's a solid reason for the async function in the first place, that seems to me like the easiest solution. I'm confused about why this bug hasn't come up before, but I can't think of anything in my setup (Windows 11, Wezterm, Mambaforge Jupyter, most recent pynvim --just in case) that would be the cause. Thanks and I'm loving Molten so far!

**Comment by sadguitarius** [comment]
Oh I forgot to add that adding 'exit_before = true' to the Hydra function also fixes the issue, although obviously I'd like the window to remain open.

**Comment by benlubas** [comment]
I'm not surprised this hasn't come up given that it's only windows machines that seem to have these issues and not too many people use Hydra. 

I'm fine converting it to sync.

**Comment by sadguitarius** [comment]
Working fine now, thank you!
