### ISSUE TITLE
[Feature Request] Default kernel launch with python on's PATH?

### ISSUE THREAD

**Issue by lkhphuc** [benlubas/molten-nvim#167]
Hey, thanks for the plugin. Just started checking this out and the default behaviour surprises me a little bit. 
When I run `MoltenInit python` (the default python3 as suggested throws a weird error "not a command"), the kernel started is from the `vim.g.python3_host_prog` variables, but not the actual python on my PATH variables, as shown in `MoltenInfo` panel.

As far as I know, the python3_host_prog is only intended for neovim and remote plugin execution, not user code execution.
Respecting the python on user's PATH would be a great step for UX.

Want:
 - Activate virtual env in terminal however you like (venv, poetry, python, ...) 
 - Start Nvim 
 - Launch 'MoltenInit python' start kernel with python on the PATH

Reason: 
- Nvim is a terminal application, so should respect terminal state.
- Launching jupyter from terminal also similar behaviour. Default kernel will that of the python's on the PATH.

Alternative:
- Set up possible environment paths as in the doc.

**Comment by benlubas** [comment]
Sorry, this seems like two problems. The `not a command` issues and then the behavior that seems weird to you, right?

Can you post more information about the error that you get? I've never seen it.

**Comment by benlubas** [comment]
About the feature request. I've had some time to look into this.

@lkhphuc do you know if this is actually possible? Do other tools do this? From my understanding of the way jupyter (and ipython) works, you need to install a kernel for the version of the language that you want to use, in the environment that you want to use it in.

This is what the molten docs suggest. It also seems to be what ipython [suggests](https://ipython.readthedocs.io/en/latest/install/kernel_install.html#kernels-for-different-environments). I don't see anything on their docs that suggest what you're asking for is possible, but if you know of something that does this definitely let me know. It would certainly be convenient.

**Comment by benlubas** [comment]
> the kernel started is from the vim.g.python3_host_prog variables, but not the actual python on my PATH variables, as shown in MoltenInfo panel

I don't see this behavior at all. If I install the regular ipython kernel, and then jump into a venv with totally different libraries available to it, `:MoltenInit python3` will still start a kernel and run code with my system python (b/c that's where the kernel was installed from). Similarly, kernels installed in venvs, only have access to the libraries in their venv.

I never see the kernel run with the version of python specified by `python3_host_prog`.

Also question: is your `:MoltenInfo` `python3` kernel changing when you change the version of python on your path with a venv? I don't see that happen, and I don't think it should.

**Comment by lkhphuc** [comment]
Hey, it seems I was confused by the terminology a little. 
It works now, though FWIW here are my steps and what confuses me:
1. Did everything like this until here : https://github.com/benlubas/molten-nvim/blob/main/docs/Virtual-Environments.md#point-neovim-at-this-virtual-environment , except I use conda env.
2. Activate a work environment (also conda), already install jupyter.
3. Run nvim
4. `MoltenInfo` shows 1 inactive kernel, `   resource_dir: /opt/homebrew/Caskroom/mambaforge/base/envs/neovim/share/jupyter/kernels/python3` where the `.../envs/neovim/...` is the conda environment in my `vim.g.python3_host_prog`
5. Run `MoltenInit` -> Select kernel to launch `python3` (the only option)
6. Get error 
```
   Error  17:11:22 msg_show.lua_error Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim:E492: Not an editor command: MoltenInit python3
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...s/phuc/.local/share/nvim/lazy/molten-nvim/lua/prompt.lua:28: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
From now on, `:MoltenInit` always throws "Not an editor command", so I restart Nvim, same step from  1 to 3:
5. Run `MoltenInit python` -> Kernel is ready
6. MoltenInfo shows 1 active and 1 inactive kernel, both points to the same resource `envs/neovim`
7. Evaluate line `!which python` correctly shows the python of my work environment.

I guess I was confused because I thought each python env with `jupyter` installed is a "kernel", plus the error when running the default MoltenInit command.

But everything is running OK for me now, looking forward to test this plugin further.
Feel free to close this issue if you can't do anything with it. Thank you.

**Comment by benlubas** [comment]
Hmm that is still an odd error to get. When I run Init with a kernel that doesn't exist I get a massive error. I should definitely handle that better. 

Most of the time I just run `:MoltenInit` without any args and select the kernel from the popup.

I'll leave this open for a little to remind myself to fix that large error I get

**Comment by akthe-at** [comment]
@lkhphuc could you run a :checkhealth for us ? I am most curious about the python areas. Could you also show your install config? @benlubas I also get issues with :Molten commands when I fail to properly set the manifest or if I mess up my Lazy loading config...

**Comment by lkhphuc** [comment]
Hi, I checked again after reading your comment @akthe-at and I didn't get an error anymore.
"MoltenInit" still shows only python3 but it ran successfully, so does "MoltenInit python".
Could it be that I updated my neovim nightly, or I update my base conda environment as well?

FWIW my lazy.nvim config:
```lua
{
    "benlubas/molten-nvim",
    build = ":UpdateRemotePlugins",
    keys = {
      { "<leader>rm", "<cmd>MoltenInit python<CR>", desc = "MoltenInit python" },
    },
    init = function()
      vim.g.molten_auto_open_output = false
      vim.g.molten_virt_text_output = true
      vim.g.molten_virt_lines_off_by_1 = true
      vim.api.nvim_create_autocmd("User", {
        pattern = "MoltenInitPost",
        callback = function()
          vim.keymap.set("n", "<CR>", "<cmd>MoltenEvaluateOperator<CR>",
            { buffer = true, silent = true, desc = "Run" }
          )
          vim.keymap.set("v", "<CR>", ":<C-u>MoltenEvaluateVisual<CR>'>",
            { buffer = true, silent = true, desc = "Run selection" }
          )
          vim.keymap.set("n", "<S-CR>", "vax<CR>]xj",
            { remap = true, buffer = true, silent = true, desc = "Run cell and move" }
          )
          vim.keymap.set("n", "<leader>rh", "<cmd>MoltenHideOutput<CR>",
            { buffer = true, silent = true, desc = "Hide Output" }
          )
          vim.keymap.set("n", "<leader>ro", "<cmd>noautocmd MoltenEnterOutput<CR>",
            { buffer = true, silent = true, desc = "Show/Enter Output" }
          )
          vim.keymap.set("n", "<leader>ri",
            "<cmd>MoltenImportOutput<CR>",
            { buffer = true, silent = true, desc = "Import Notebook Output" }
          )
        end,
      })
    end,
  }
```
Thanks again for your help and the great plugin.

**Comment by benlubas** [comment]
Nightly recently had some breaking bugs, so I wouldn't be surprised, I'm also pretty sure that the import/export functions in this plugin are broken on nightly.
