### ISSUE TITLE
[Help] Running full blocks

### ISSUE THREAD

**Issue by slatifi** [benlubas/molten-nvim#169]
I have just setup Molten (and all of its other dependencies) and am able to run code in notebooks. However, I find I am using the virtual operator (`MoltenEvaluateVisual`) or when using the `MoltenEvaluateOperator` I am counting the lines in the cell. 

I feel that there must a better way to run all of the code within the backticks (i.e. the block). Please help!

For reference, I was following the [Notebook-Setup](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md) guide and previously the [Not So Quick Start Guide](https://github.com/benlubas/molten-nvim/blob/main/docs/Not-So-Quick-Start-Guide.md)

I have also not been able to map custom keys for the commands - instead it just acts as the keys normally do (i.e. <leader>je will move a line down and a word across). Below is my config for all related plugins:

`
return {

    {
        "benlubas/molten-nvim",
        version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
        dependencies = { "3rd/image.nvim" },
        build = ":UpdateRemotePlugins",
        init = function()
            -- these are examples, not defaults. Please see the readme
            vim.g.molten_image_provider = "image.nvim"
        end,
        keys = {
            {"n", "<leader>je", "<cmd>MoltenEvaluateOperator<cr>", {desc = "evaluate operator", silent=true}},
            {"v", "<leader>je", "<cmd><C-u>MoltenEvaluateVisual<CR>gv", {desc = "evaluate cell", silent=true}},
            {"n", "<leader>jx", "<cmd>MoltenReevaluateCell<cr>", {desc = "re-evaluate cell", silent=true}},
            {"n", "<leader>jd", "<cmd>MoltonDelete<cr>", {desc = "delete output", silent=true}},
            {"n", "<leader>js", "<cmd>MoltenShowOutput<cr>", {desc = "show output", silent=true}},
            {"n", "<leader>jh", "<cmd>MoltenHideOutput<cr>", {desc = "hide output", silent=true}},
            {"n", "<leader>jx", "<cmd>MoltenReevaluateCell<cr>", {desc = "re-evaluate cell", silent=true}},
        }
    },
    {
        -- see the image.nvim readme for more information about configuring this plugin
        "3rd/image.nvim",
        opts = {
            backend = "kitty", -- whatever backend you would like to use
            max_width = 100,
            max_height = 12,
            max_height_window_percentage = math.huge,
            max_width_window_percentage = math.huge,
            window_overlap_clear_enabled = true, -- toggles images when windows are overlapped
            window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
        },
    },
    {
        "quarto-dev/quarto-nvim",
        ft = {"quarto", "markdown"},
        opts = {
            lspFeatures = {
                languages = { "r", "python", "rust" },
                chunks = "all",
                diagnostics = {
                    enabled = true,
                    triggers = { "BufWritePost" },
                },
                completion = {
                    enabled = true,
                },
            },
            keymap = {
                hover = "H",
                definition = "gd",
                rename = "<leader>rn",
                references = "gr",
                format = "<leader>gf",
            },
            codeRunner = {
                enabled = true,
                default_method = "molten",
            },
        }
    },
    {
        "jmbuhr/otter.nvim",
    },
    {
        "GCBallesteros/jupytext.nvim",
        opts = {
            style = "markdown",
            output_extension = "md",
            force_ft = "markdown",
        }
    }
}
`

Thank you for all your help - as I'm sure you can tell I'm quite new to the neovim environment and really enjoying it so far.

**Comment by benlubas** [comment]
For the first problem where you're counting lines of the cell, I would recommend setting up a text object for code blocks. Text objects are a vim concept, when you do `yip` for example to yank the inner paragraph, `p` is the text object. You can define custom ones using treesitter with the nvim-treesitter-textobjets plugin. Instructions for how to do that are in the notebook setup hidden [towards the bottom](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md#treesitter-text-objects). 

If you have more questions about that lmk.

---

Keybinds aren't working probably because lazy key mappings don't take a table with desc, silent, etc. They're just passed as keys. (this is something really annoying that lazy does that's just different to the normal `vim.kymap.set` for no apparent reason.)

so instead of this:

```lua
{"n", "<leader>je", "<cmd>MoltenEvaluateOperator<cr>", {desc = "evaluate operator", silent=true}},
```

try this:

```lua
{"n", "<leader>je", "<cmd>MoltenEvaluateOperator<cr>", desc = "evaluate operator", silent=true},
```

and then make that same change for the rest of your mappings too.

Lmk if you have other questions, glad you're enjoying neovim so far!

**Comment by slatifi** [comment]
Thank you @benlubas. I have since tried setting up the quarto runner instead as I understand that it can run the code blocks for you? I amended my configuration to the below but I now just get the error:

> [Quarto] it seems that the code runner isn't initialized for this buffer.

even though I had run `MoltenInit` and the other Molten commands work fine. 

My config for quarto:

`{

        "quarto-dev/quarto-nvim",
        ft = {"quarto", "markdown"},
        config = function ()
            require("quarto").setup({
                lspFeatures = {
                    languages = { "r", "python", "rust" },
                    chunks = "all",
                    diagnostics = {
                        enabled = true,
                        triggers = { "BufWritePost" },
                    },
                    completion = {
                        enabled = true,
                    },
                },
                keymap = {
                    hover = "H",
                    definition = "gd",
                    rename = "<leader>rn",
                    references = "gr",
                    format = "<leader>gf",
                },
                codeRunner = {
                    enabled = true,
                    default_method = "molten",
                }
            })
            local runner = require("quarto.runner")
            vim.keymap.set("n", "<localleader>rc", runner.run_cell,  { desc = "run cell", silent = true })
            vim.keymap.set("n", "<localleader>ra", runner.run_above, { desc = "run cell and above", silent = true })
            vim.keymap.set("n", "<localleader>rA", runner.run_all,   { desc = "run all cells", silent = true })
            vim.keymap.set("n", "<localleader>rl", runner.run_line,  { desc = "run line", silent = true })
            vim.keymap.set("v", "<localleader>r",  runner.run_range, { desc = "run visual range", silent = true })
            vim.keymap.set("n", "<localleader>RA", function()
                runner.run_all(true)
            end, { desc = "run all cells of all languages", silent = true })
        end
    },
`

**Comment by benlubas** [comment]
> [Quarto] it seems that the code runner isn't initialized for this buffer.

This is what you get when you try to run in a buffer where `:QuartoActivate` hasn't been called. I guess you're in a plain markdown buffer. So you can run that command automatically or you can get an ftplugin (another vim concept) to do it for you.

This is also mentioned in the notebook setup [here](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md#activate-quarto-nvim-in-markdown-buffers). That also lets you know how to setup the ftplugin to activate quarto in markdown buffers automatically.

**Comment by slatifi** [comment]
Ah that fixed it, thank you! :)
