### ISSUE TITLE
[Help] Treesitter text objects not loading

### ISSUE THREAD

**Issue by slatifi** [benlubas/molten-nvim#170]
I have been following the [Notebook Setup](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md#treesitter-text-objects) guide (which is excellent by the way, thank you @benlubas) and have been able to set up all the features described, including the output chunks, apart from the treesitter text objects config. I followed the guide and added the textobjects.scm at the recommend path (~/.config/nvim/after/queries/markdown/textobjects.scm) and added the following to my plugin config:

`{
   
    "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        dependencies = { "nvim-treesitter/nvim-treesitter-textobjects"},
        config = function()
            require("nvim-treesitter.configs").setup({
                ensure_installed = { "c", "lua", "vim", "vimdoc", "query" },
                auto_install = true,
                highlight = { enable = true },
                indent = { enable = true },
                textobjects = {
                    move = {
                        enable = true,
                        set_jumps = false, -- you can change this if you want.
                        goto_next_start = {
                            --- ... other keymaps
                            ["]b"] = { query = "@code_cell.inner", desc = "next code block" },
                        },
                        goto_previous_start = {
                            --- ... other keymaps
                            ["[b"] = { query = "@code_cell.inner", desc = "previous code block" },
                        },
                    },
                    select = {
                        enable = true,
                        lookahead = true, -- you can change this if you want
                        keymaps = {
                            --- ... other keymaps
                            ["ib"] = { query = "@code_cell.inner", desc = "in block" },
                            ["ab"] = { query = "@code_cell.outer", desc = "around block" },
                        },
                    },
                    swap = { -- Swap only works with code blocks that are under the same
                        -- markdown header
                        enable = true,
                        swap_next = {
                            --- ... other keymap
                            ["<leader>sbl"] = "@code_cell.outer",
                        },
                        swap_previous = {
                            --- ... other keymap
                            ["<leader>sbh"] = "@code_cell.outer",
                        },
                    },
                }
            })
        end`

However, the binding don't seem to have any effect - `vib` does not select the inside of the code block. Any ideas?

**Comment by benlubas** [comment]
`;extends` has to be the first line in that scm file. I should make that more clear.

**Comment by slatifi** [comment]
Ah yep, that fixed it. Thanks.
