### ISSUE TITLE
[Help] Molten Not in a Cell / [Quarto It seems that the code runner is not initalized for this buffer

### ISSUE THREAD

**Issue by jmrussell** [benlubas/molten-nvim#174]
I'm trying to configure molten/quarto for use in both .qmd and .ipynb file formats. I can send individual lines and visual selections via molten (configured with the suggested keybindings) but when I try running "RerunCell" I get the molten error, and when I try sending via Quarto I get the code runner not initialized error.

My workflow is open .ipynb -> it converts to .md -> run magma init (successfully) -> try to send code block using either quarto or magma bindings.

It seems that it works as expected in a .qmd file

Below is my config:

```
return {
  {
    "quarto-dev/quarto-nvim",
    opts = {
      debug = false,
      closePreviewOnExit = true,
      lspFeatures = {
        enabled = true,
        chunks = "curly",
        languages = { "r", "python", "julia", "bash", "html" },
        diagnostics = {
          enabled = true,
          triggers = { "BufWritePost" },
        },
        completion = {
          enabled = true,
        },
      },
      codeRunner = {
        enabled = true,
        default_method = "molten", -- 'molten' or 'slime'
        ft_runners = {}, -- filetype to runner, ie. `{ python = "molten" }`.
        -- Takes precedence over `default_method`
        never_run = { "yaml" }, -- filetypes which are never sent to a code runner
      },
      keymap = {
        -- set whole section or individual keys to `false` to disable
        hover = "K",
        definition = "gd",
        type_definition = "gD",
        rename = "<leader>lR",
        format = "<leader>lf",
        references = "gr",
        document_symbols = "gS",
      },
    },
  },
  { "jmbuhr/otter.nvim" },
  { "benlubas/molten-nvim", build = ":UpdateRemotePlugins" },
  {
    "GCBallesteros/jupytext.nvim",
    opts = {
      style = "markdown",
      output_extension = "md",
      force_ft = "markdown",
    },
  },
}
``` 

I'm sure I'm missing something stupid, but can't seem to find it in the docs.

**Comment by benlubas** [comment]
> when I try running "RerunCell" I get the molten error

This is b/c molten's concept of a cell and markdown or quarto's concept of a cell are different. Molten doesn't know about the file format you're using, it just knows "this text is text someone told me to run, I'll keep track of that"[^1]. 

A molten cell is just something that's been previously run, basically.

If you want to use molten to run code in a markdown cell, there are two ways to do that. The easiest I think is to just use the quarto-nvim plugin which has a code running integration with molten that I wrote. There's some extra setup (like two lines) to get it to work for markdown by default. Detailed [here](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md#activate-quarto-nvim-in-markdown-buffers).

The other way to is use a treesitter text object, detailed [here](https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md#treesitter-text-objects)

> when I try sending via Quarto I get the code runner not initialized error

This is likely b/c you're in a plain markdown file and quarto isn't auto initializing itself. running: `:QuartoActivate` in the markdown buffer should fix that, or you can follow the steps I linked above to make it happen automatically.

[^1]: Doing it this way allows molten to run code anywhere with little friction. For example, I can use molten to run: normal python, python in a markdown file, python in a norg file, a python example in some html, etc. etc. And sub that language out for any of the languages that have a jupyter kernel (which is a long list).

**Comment by jmrussell** [comment]
First off thanks for the quick response - I appreciate that, I think you have a really cool thing going here between this and integrating with quarto etc.

When I open a .ipynb and it's convert to markdown, I can run Lazy and see that Quarto is activated - if I then try the Quarto command to send the chunk (again, using their suggest keymaps to call quarto.runner's send cell function), I get 

"No code chunks found for the current language, which is detected based on the current code block. Is your cursor in a code block?"

Of course, my cursor is in a code block. In my quarto config, I do enable the code runner and set molten to be the default. Again, the molten send line command works here, so I suspect that it's an issue with quarto talking to molten, does that sound right?

Gah, sorry for opening and closing, I'm using vimium and got a little crazy with the hotkeys.

**Comment by benlubas** [comment]
that error is just an otter or quarto problem.

> run Lazy and see that Quarto is activated

Lazy can tell you that quarto is _loaded_, quarto being 'activated' means something a little different. can you run `:QuartoActivate` in the buffer and then try to run the code?

hopefully that should work

**Comment by jmrussell** [comment]
I get the same error after running QuartoActivate. 

I didn't add any config options to otter and I thought my quarto config was right, but knowing that molten is working as intended is enough to let me dive further in, especially since it's working in with the `quarto` ft.

**Comment by benlubas** [comment]
Actually, looking at your config, `chunks = "curly",` should be `chunks = "all"`

Missed that sorry

**Comment by jmrussell** [comment]
Solved by adding chunks all. Thank you! Now once I can get the images working (or even just opening in an external x11 window if possible) I will never have to use jupyter notebook again and for that I'll be eternally grateful.

**Comment by benlubas** [comment]
sweet! glad that worked.
