### ISSUE TITLE
[Help] Virtual Text offset apply only to output text?

### ISSUE THREAD

**Issue by hahuang65** [benlubas/molten-nvim#178]
```
vim.g.molten_virt_lines_off_by_1 = true
```

makes it such taht the output is outside the code fence markers...

But I also use virtual text for my diagnostics. This makes all the LSP diagnostics appear 1 line lower than where they actually should be.

Is there any way to have the offset ONLY apply to the output text?

**Comment by benlubas** [comment]
Molten doesn't have anything to do with diagnostics, that option shouldn't (doesn't) affect diagnostics at all.

**Comment by hahuang65** [comment]
That's what I thought should be the case, but it doesn't seem to be.

![Screenshot 2024-04-03 at 18 38 18](https://github.com/benlubas/molten-nvim/assets/280972/46be9249-7976-4495-89fa-9db5db68865a)
![Screenshot 2024-04-03 at 18 39 10](https://github.com/benlubas/molten-nvim/assets/280972/8320e3dd-1870-42ed-ab83-18974187138c)

The only change is `vim.g.molten_virt_lines_off_by_1 = true`

**Comment by benlubas** [comment]
this could possibly be the weirdest bug I've ever encountered. Which plugin are you using for the pretty diagnostics? I can look into it.

assuming that it's lsp-lines

**Comment by hahuang65** [comment]
> assuming that it's lsp-lines

yup

**Comment by benlubas** [comment]
I'm not able to replicate this :/

**Comment by benlubas** [comment]
If you could provide a minimal configuration that can still replicate it that'd be great.

There's a minimal config in the docs folder, you can start with that, add otter and lsp lines, and the provide a simple example and what you do to get the bug to occur. If it still reproduces then I can debug. If it doesn't, then we know it's somewhere else in your config and we can look into that.

**Comment by hahuang65** [comment]
@benlubas thanks for looking into it. I'll try to get a minimal reproducible config tomorrow and let you know :)

**Comment by hahuang65** [comment]
Okay, very curious. I was trying to make a minimal reproduction config, but got stuck at getting Quarto to run. It just wouldn't run, neither would otter.

So I tried a wholesale copy of my existing config, and was going to remove config bit by bit until the issue resolved... which is when I noticed something.

If I open the file directly with `nvim notebooks/notebook.ipynb`, Quarto does NOT activate automatically. I have to run `:QuartoActivate`... at which point, the diagnostics are on the correct line.

However, if I open `nvim .` and use netrw to navigate to `notebooks/notebook.ipynb`, Quarto will automatically run... and the diagnostics will be off by 1.

**Comment by hahuang65** [comment]
Right, so if I just remove

```
local ok, quarto = pcall(require, "quarto")
if ok then
  quarto.activate()
end
```

which is the contents of `after/ftplugin/markdown.lua` then I have to manually activate... which "fixes" the issue.

I've also tried moving it to `ftplugin/markdown.lua` instead, thinking it might be an order of operations issue, but that results in teh same off-by-1 behavior.

**Comment by benlubas** [comment]
Does it still happen without molten installed?

**Comment by hahuang65** [comment]
Aha! Yes, it DOES still happen with molten removed from the equation. I'm guessing this is an otter issue then.
