### ISSUE TITLE
[Help] Same config on Arch Linux not working

### ISSUE THREAD

**Issue by hahuang65** [benlubas/molten-nvim#179]
Is there a way to debug the error message on `:MoltenInit` if it tells me `Could not initialize kernel named 'MyKernel'`?

Is there a log somewhere I can look at?

My exact some config works on macOS but is giving me this error on my Linux machine.

**Comment by benlubas** [comment]
run `:MoltenInfo` and make sure there's a kernel named "MyKernel" if not, you need to install one

**Comment by hahuang65** [comment]
Yeah, the kernel does exist. But Molten can't seem to start it.

**Comment by hahuang65** [comment]
Any other recommendations here? I really can't quite figure out why Molten is failing to start the kernel.

**Comment by benlubas** [comment]
Yes sorry, lots going on. You can start the kernel externally and connect to it. Or reinstall the kernel with `--user`. Instructions for both in the docs.

External stuff is in advanced usage.

Installing the kernel is in the virtual envs docs (you don't have to use a venv, but it's generally good practice). You can ignore the venv stuff and just find the command there. You probably don't have to provide a name either.

**Comment by hahuang65** [comment]
Yup, I've actually got code that auto-detects which kernel name should be used when I open a ipynb, and installs it in the venv with `--user`, then `MoltenInit`s it.

https://github.com/hahuang65/nvim-config/blob/f6db475ad3a10ff54624a4dc5ad2843ceaecbe32/after/ftplugin/markdown.lua#L10

This works beautifully on my Mac, but not on Arch. The kernel starts fine outside of Molten. I'd like to try to figure out what Molten is failing on so I don't have to start it externally.

Are there any error logs that Molten logs out to, or will I just have to debug inside the plugin?

**Comment by benlubas** [comment]
Do you have to `:wait()` on the second system command?

and does running the command manually still fail I guess?

The other thing that I could think, is that vim.system has a slightly weird environment iirc, so things might not install in all the right places.

**Comment by hahuang65** [comment]
I think this was PEBKAC. I must have not had the right Python version installed for that virtual env and it was erroring out. In any case, it's working now. Feel free to close, and sorry for the trouble.

**Comment by benlubas** [comment]
@hahuang65 anything I can do to make the error more visible/clearer? happy to do that or accept a PR

**Comment by hahuang65** [comment]
Lemme take a look and see what might be good. I'll get back to you on that.

**Comment by hahuang65** [comment]
@benlubas Wondering if we could expose the error here
https://github.com/benlubas/molten-nvim/blob/66b11de7c3132dcc4521d50039ce2b5f81e64ca2/rplugin/python3/molten/__init__.py#L206

Either as part of the notification, in `:messages`, or in some log, like how `LspLog` does it.

That would really aid in debugging what the issue is when calling a kernel fails to initialize.

**Comment by benlubas** [comment]
@hahuang65 thank you for looking into that! I'll make that more visible in a couple days when I have some time.

**Comment by igorlfs** [comment]
Hello!

I was having a similar issue. It's been a while since I last used molten, but I came back this week. I'm also on arch. 

I was following the venv guide, but I got this error:

```
[Molten] Could not initialize kernel named 'my-kernel'.
Caused By: [Errno 2] No such file or directory: '~/.local/share/jupyter/runtime/kernel-fbe03fd3-b3b0-4310-b903-da9079da1ae7.json'
```

And sure enough, this file didn't exist. In fact, the directory `~/.local/share/jupyter/runtime` didn't exist.

When I ran

```sh
python -m ipykernel
```

The directory was created, along with a file with a different `uuid`, and I then I could use `:MoltenInit` and so on.

My guess is that somehow molten expects the runtime dir to exist, and newer versions of ipykernel are no longer creating it, or something like that.

**Comment by benlubas** [comment]
Molten creates a file there when it starts a kernel so that other applications can find the running kernel and connect to it if they want. This enables the use of other jupyter plugins.

If I had to guess, we probably do expect that folder to already exist, I will take a look and probably just add a few lines to check for it and create it if it's missing.

**Comment by benlubas** [comment]
This might actually be considered a bug in `jupyter_client`'s `write_connection_file` function

https://github.com/jupyter/jupyter_client/blob/main/jupyter_client/connect.py#L156-L157

Molten doesn't handle writing the file, we call that function here: 

https://github.com/benlubas/molten-nvim/blob/f3a40c744d177862682f0787eef7e5ab0f4e0118/rplugin/python3/molten/runtime.py#L63

**Comment by jackruder** [comment]
Had a similar issue on Arch, and manually creating the runtime directory solved my issue.

**Comment by romain-bury** [comment]
I was actually also struggling with that issue until I came accross this discussion. It would probably be helpful to explain the solution in the docs ?
