### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by benlubas** [benlubas/molten-nvim#2]
- [x] Add new function, `MoltenUpdateOption` to the readme
- [x] multi buffer support
- [x] Change Border Configuration option to take any value that can be passed to nvim open win border option
- [x] Setup the Wiki
    - [x] Quickstart guide
    - [x] Python Virtual environment setup
    - [x] Setups/Integrations guides (ie. quarto, and quarto code runner)
- [x] Create a feature test file
    - [x] Write contributing.md and mention the feature test file
- [x] Output window redraw optimizations to remove flicker when:
    - [x] The main window is scrolled and output moves
    - [x] More output is added to the buffer
- [x] Output can show an image that overlaps the status bar
- [x] A couple image.nvim bugs
- [x] Inherited a broken save/load system that I'd like to fix
- [x] When you're in the output window and quit it, your cursor leaves, but it reopens. This is slightly annoying. Should be configurable.
- [x] `:MoltenHideOutput` doesn't work from within the output
- [x] Windows aren't disappearing on window changed
- [x] Render a "more output" footer or something when the window is shorter than the buffer contents

**Comment by phcerdan** [comment]
Amazing work @benlubas, I am switching right away from magma to molten :)

Thanks!
