### ISSUE TITLE
[Help] Looking for a minimal example for quickly and directly Displaying SVG paths in nvim image

### ISSUE THREAD

**Issue by MikeLemo1** [benlubas/molten-nvim#205]
[Help] Looking for a minimal example for quickly and directly Displaying SVG paths in nvim image

**Comment by benlubas** [comment]
just opening the file while image.nvim is installed and configured will display the SVG for you. 

But I think you're asking for how to do it in molten, in which case... let me look into that

**Comment by benlubas** [comment]
This works for me!
```python
from IPython.display import display
from IPython.core.display import SVG
display(SVG('<svg height="100" width="100" xmlns="http://www.w3.org/2000/svg"> <circle r="45" cx="50" cy="50" fill="red" /> </svg>'))
```

**Comment by MikeLemo1** [comment]
Huh for some reason this doesn't show me an image output in nvim but does in jupyter

**Comment by MikeLemo1** [comment]
Ok so tried it with `version = "1.1.0",` and it does the job displaying svg's so *this doesn't work with today's version.

Meaning it displays some small black rect that moves a little at the start instead of a red circle with black rect margin.

**Comment by benlubas** [comment]
for image.nvim or for molten?

I'm running latest image.nvim and latest molten and I'm seeing the image as normal

**Comment by MikeLemo1** [comment]
> for image.nvim or for molten?
> 
> I'm running latest image.nvim and latest molten and I'm seeing the image as normal

I was talking about `version = "1.1.0",` of `molten-nvim`

**Comment by benlubas** [comment]
How did you settle on such an old version of molten? Did all the others not work for you?

**Comment by MikeLemo1** [comment]
> How did you settle on such an old version of molten? Did all the others not work for you?

No just went with the version specified in the documentation and it works and I settled on that because I don't care about the other million versions that also work exept the latest.

**Comment by benlubas** [comment]
Can you link the docs where that is. I'll update it bc 1.1.0 is pretty long ago now

**Comment by MikeLemo1** [comment]
Sure thing:
https://github.com/benlubas/molten-nvim/blob/main/docs/Not-So-Quick-Start-Guide.md

**Comment by benlubas** [comment]
There's an image.nvim version 1.1.0, I should up that to 1.3.0 now. But I don't see anything that gives an old molten version

**Comment by MikeLemo1** [comment]
Maybe I took it from the sample:
https://github.com/benlubas/molten-nvim/blob/main/docs/Not-So-Quick-Start-Guide.md#sample-lazynvim-config
