### ISSUE TITLE
[Help] What's are the difference between `dccsillag/magma-nvim` and `benlubas/molten-nvim`?

### ISSUE THREAD

**Issue by MikeLemo1** [benlubas/molten-nvim#206]
Trying to choose a code runner for python, and was wondering what's are the difference between `dccsillag/magma-nvim` and `benlubas/molten-nvim`?

**Comment by benlubas** [comment]
Change log is there if you want a full picture.

Briefly, this plugin uses image.nvim to display images, we have virtual text (though buggy), we have significantly less buggy and more performant floating windows than magma, we have a maintainer (me, although I don't use this plugin that much anymore :/  I'm still happy to answer questions and review PRs), we have .ipynb import/export, open html in browser, execution time, virtual text under floating windows so they don't cover your document. The list goes on.

This plugin is basically magma + all the things that I was missing when I used magma (+ a bunch of bug fixes). I wanted to use magma in college where I needed to work with jupyter notebooks, and I found that it was a little buggy and needed a little love, the maintains weren't around, so I forked it and made molten.

I'm not even sure that magma will work at the moment without using someone's fork, so I'd recommend using this plugin!

**Comment by benlubas** [comment]
and b/c you just say code runner, there are plenty of other fantastic options. https://github.com/michaelb/sniprun and https://github.com/Olical/conjure are the two I'd look into.

They differ from molten in that they're "general purpose" and molten is _just_ for Jupyter Kernels (btw, this isn't as limiting as it sounds [here's](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) a list), and molten is designed for a "notebook" type experience. But it does work and I do use it in normal files. While developing molten if I was ever like "how does that work in python again" I'd just run an example with molten.

Molten has image support, others do not as far as I know.
