### ISSUE TITLE
[Help] Opening output in new buffer

### ISSUE THREAD

**Issue by AlejandroGomezFrieiro** [benlubas/molten-nvim#207]
I know it is possible to enter the output, but is it possible to open the output in a new buffer?

**Comment by benlubas** [comment]
I think there's some confusing terminology here. 

Entering the output _is_ opening it in a new buffer. 

I think you want it opened in a split buffer which doesn't go away? Currently there is no (easy) way to do that, but you could create a key bind to copy all the text content into a split. Unfortunately that would not work for images. 

You might be able to open a split, open the float, enter it, grab the buf number, and then open the buffer in the split before exiting the float. And still exiting the float might delete the buffer I forget how exactly it's coded. But it also might not. Which would potentially yield the result you want.

**Comment by kalyanoliveira** [comment]
What I usually do is enter the output window, and use CTRL-W CTRL-T. That just takes any buffer and moves it into a new tab.

**Comment by benlubas** [comment]
Just tested and `CTRL-W_CTRL-S` also works! also `CTRL-W_CTRL-V` if you prefer a vertical split. Thanks @kalyanoliveira!
