### ISSUE TITLE
[Bug] <Your title here>

### ISSUE THREAD

**Issue by eldar** [benlubas/molten-nvim#216]
- OS: Nix
- NeoVim Version: 0.10.1
- Python Version: 3.10
- Python is installed with: conda
- Health checks

<details>
  <summary>`:checkhealth molten`</summary>

```

==============================================================================
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- WARNING Optional python module cairosvg not found
  - ADVICE:
    - pip install cairosvg
- WARNING Optional python module pnglatex not found
  - ADVICE:
    - pip install pnglatex
- WARNING Optional python module plotly not found
  - ADVICE:
    - pip install plotly
- WARNING Optional python module kaleido not found
  - ADVICE:
    - pip install kaleido
- WARNING Optional python module pyperclip not found
  - ADVICE:
    - pip install pyperclip
- OK Python module nbformat found
- OK Python module pillow found
```

</details>

## Description
Molten fails to open a jupyter notebook file properly and instead shows it as plain text (JSON).

![jupyter_notebook](https://github.com/user-attachments/assets/d2b413c6-67ad-4769-8409-c80192e1f298)

## Reproduction Steps

I followed the instructions from here: https://github.com/benlubas/molten-nvim/blob/main/docs/Probably-Too-Quick-Start-Guide.md, namely, I installed Molten via Lazy as well as installed the required dependencies on the python side. Here's the plugin spec from Lazy:

```lua
return {
  "benlubas/molten-nvim",
  version = "^1.0.0",   -- use version <2.0.0 to avoid breaking changes
  build = ":UpdateRemotePlugins",
  init = function()
    -- this is an example, not a default. Please see the readme for more configuration options
    vim.g.python3_host_prog=vim.fn.expand(".venv/bin/python3")
    vim.g.molten_output_win_max_height = 12
  end,
}
```

I tried executing `:MoltenInit` but Neovim says: `E492: Not an editor command: MoltenInit`.

## Expected Behavior
I expect the notebook file to be opened and displayed as a notebook. Probably I am missing something obvious, but the plugin is loaded and healthcheck seems OK, so I'm out of ideas. Thanks!

**Comment by benlubas** [comment]
Molten doesn't handle opening jupyter notebook files. Have a look at the notebook setup guide in the docs
