### ISSUE TITLE
[Help] Annoying "--No lines in buffer--" message

### ISSUE THREAD

**Issue by litaxc** [benlubas/molten-nvim#217]
When the cell output window is displayed, the command line area will show a message with `--No lines in buffer--`. The message can be cleaned with the `^L` key, but it will reappear soon after `g:molten_tick_rate`.
The message is probably coming from [this line](https://github.com/benlubas/molten-nvim/blob/eb6d0fe33e14989b0f1fbe25d9732889ee57bd1a/rplugin/python3/molten/outputbuffer.py#L294)
`self.nvim.funcs.deletebufline(self.display_buf.number, 1, "$")`
Is there a way to silence the output?

**Comment by litaxc** [comment]
@benlubas Thank you for the quick fix! Really appreciate it.

**Comment by benlubas** [comment]
Thanks for pointing me to the exact line causing the problem!
