### ISSUE TITLE
[FIXED] [Bug] kernel does not start

### ISSUE THREAD

**Issue by MrMic** [benlubas/molten-nvim#225]
Hi,

- I work with AstroNvim and have installed molten.
- I work in a project that is OK with `jupyter notebook`
- When I put `:MoltenInit` the list of kernels is OK (see screenshot) but when 
I press to confirm the right kernel I got an error (see screenshot).
- The `:checkhealth molten` is OK!

- NVIM v0.10.1
- Python 3.10.2

Any idea what is wrong?

Rgds,

![Capture d’écran du 2024-08-22 10-32-19](https://github.com/user-attachments/assets/7698b52a-f196-44f4-b597-4e6be3acef33)

![Capture d’écran du 2024-08-22 10-33-18](https://github.com/user-attachments/assets/234613e8-006a-4634-9846-0127187712b0)

![Capture d’écran du 2024-08-22 10-43-10](https://github.com/user-attachments/assets/96976fe8-df9e-40f5-8b70-c78f2e46b562)

**Comment by benlubas** [comment]
What operating system? 
Did you run `:UpdateRemotePlugins`?
Does it work if you disable whatever is changing your selection menu?

**Comment by MrMic** [comment]
- I am on Ubuntu 22.04
- Already run `:UpdateRemotePlugins`
- Do not understand your last question.  An example?

**Comment by benlubas** [comment]
oh right. Astro. 

Look up what plugin is changing your vim.ui.select menu and disable it. (You might have to ask in their discord). It's probably dressing.nvim. I'd be surprised if that fixes it but I want to rule it out. 

I also want to make sure you're on the latest version of molten.

**Comment by MrMic** [comment]
The config is as follow:
```
---@type LazySpec
return {
  "benlubas/molten-nvim",
  cmd = {
    "MoltenInfo",
    "MoltenInit",
    "MoltenDein",
    "MoltenGoto",
    "MoltenNext",
    "MoltenPrev",
    "MoltenEvaluateLine",
    "MoltenEvaluateVisual",
    "MoltenEvaluateOperator",
    "MoltenEvaluateArgument",
    "MoltenReevaluateCell",
    "MoltenDelete",
    "MoltenShowOutput",
    "MoltenHideOutput",
    "MoltenEnterOutput",
    "MoltenInterrupt",
    "MoltenOpenInBrowser",
    "MoltenImagePopup",
    "MoltenRestart",
    "MoltenSave",
    "MoltenLoad",
    "MoltenExportOutput",
    "MoltenImportOutput",
  },
  version = "^1", -- use version <2.0.0 to avoid breaking changes
  build = ":UpdateRemotePlugins",
  dependencies = {
    "AstroNvim/astrocore",
    opts = function(_, opts)
      if not opts.mappings then opts.mappings = {} end
      local prefix = "<leader>m"

      opts.mappings.n[prefix .. "mi"] = { "<Cmd>MoltenInit<CR>", desc = "Initialize the plugin" }
      opts.mappings.n[prefix .. "e"] = { "<Cmd>MoltenEvaluateOperator<CR>", desc = "Run operator selection" }
      opts.mappings.n[prefix .. "rl"] = { "<Cmd>MoltenEvaluateLine<CR>", desc = "Evaluate line" }
      opts.mappings.n[prefix .. "rr"] = { "<Cmd>MoltenReevaluateCell<CR>", desc = "Re-evaluate cell" }
      opts.mappings.v[prefix .. "r"] = { ":<C-u>MoltenEvaluateVisual<CR>gv", desc = "Evaluate visual selection" }
    end,
  },
}
```
No dressing.nvim plugin.

**Comment by benlubas** [comment]
Part of astro core is changing the default `vim.ui.select` then.

I'd also suggest removing the `cmd = ` part for now, just to make sure that's not interfering with it.

**Comment by MrMic** [comment]
Am I supposed to do something? 
Do you think you're going to fix your app to make it work?

**Comment by benlubas** [comment]
We'll see the thing is. It does work. For me. And everyone else. So you need to help me reproduce the issue you're having so that I can fix it. 

Give me a reproduction with as few plugins as possible (Astro core counts as a ton of plugins), and I'll look into it when I have time. 

I'm very busy with life right now so I can't promise when that will be.

**Comment by mehalter** [comment]
@benlubas you are correct with your suggestion. It is just the plugin not playing well with lazy loading on command. Removing the `cmd` makes it work perfectly. This can be closed.

**Comment by MrMic** [comment]
Indeed this works now.
