### ISSUE TITLE
[Bug] Error initializing Molten with MoltenInit: "Could not initialize kernel named 'python3'"

### ISSUE THREAD

**Issue by LuisHernandez2508** [benlubas/molten-nvim#233]
Hi, I encountered an issue when trying to initialize Molten using MoltenInit. The error message states that it could not initialize the python3 kernel.

- OS: Manjaro 6.9.12-3
- NeoVim Version: 0.10.1
- Python Version: 3.12.5
- Health checks:
- molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- OK Python module cairosvg found
- OK Python module pnglatex found
- OK Python module plotly found
- OK Python module kaleido found
- OK Python module pyperclip found
- OK Python module nbformat found
- OK Python module pillow found

 Molten Info
 Initialized: true

 1 inactive kernel(s):

 Kernel: python3 
   language:     python
   cmd:          python -m ipykernel_launcher -f {connection_file}
   resource_dir: /home/luish/.local/share/jupyter/kernels/python3

## Error message:
[Molten] Could not initialize kernel named 'python3'.
Caused By: [Errno 2] No such file or directory: '/home/luish/.local/share/jupyter/runtime/kernel-2e290922-e7b2-40af-9f44-b059bb43aa13.json'
Kernel: python3
![2024-09-06-122758_2160x1440_scrot](https://github.com/user-attachments/assets/15af3187-6b76-4d48-b7b1-b377dc7c7a15)

## Description
I expected Molten to initialize with the python3 kernel, but the kernel failed to load with the error above. Any advice or help on resolving this issue would be greatly appreciated.

## Reproduction Steps
Run MoltenInit.
Select the python3 kernel.
The error message appears.

**Comment by benlubas** [comment]
run `mkdir -p ~/.local/share/jupyter/runtime`

Hopefully that will fix it. Although normally you get a different error for this problem so it might be something else

**Comment by LuisHernandez2508** [comment]
Thanks! It worked perfectly. Appreciate your help!
