### ISSUE TITLE
No access to any of the Molten specific commands (No editor command `MoltenInit`)

### ISSUE THREAD

**Issue by t-ober** [benlubas/molten-nvim#235]
- OS: macOS 14.6.1
- NeoVim Version: 0.10.1
- Python Version: 3.11.4
- Python is installed with: Pyenv (Created venv as outlined in docs)
- Health checks
```
==============================================================================
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- OK Python module cairosvg found
- OK Python module pnglatex found
- OK Python module plotly found
- OK Python module kaleido found
- OK Python module pyperclip found
- WARNING Optional python module nbformat not found
  - ADVICE:
    - pip install nbformat
- OK Python module pillow found

==============================================================================
```
and `checkhealth python`:

```
==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- pyenv: Path: /Users/thomas/.pyenv/libexec/pyenv
- pyenv: Root: /Users/thomas/.pyenv
- Using: g:python3_host_prog = "/Users/thomas/.virtualenvs/neovim/bin/python3"
- Executable: /Users/thomas/.virtualenvs/neovim/bin/python3
- Python version: 3.11.4
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- $VIRTUAL_ENV is set to: /Users/thomas/.virtualenvs/neovim
- Python version: 3.11.4
- OK $VIRTUAL_ENV provides :!python.

```

## Description
Even though I get no specific error message, I can't access any of the Molten commands e.g. `MoltenInit` and thus can't access any functionality. (No editor command `MoltenInit`). 

## Reproduction Steps
I'll try to figure that part out soon.

## Expected Behavior
Access to `MoltenInit` to initialize the plugin.

**Comment by benlubas** [comment]
did you run `:UpdateRemotePlugins`?

**Comment by t-ober** [comment]
Damn it! Couldn't execute the command and found some confusing information on the interwebz and then forgot about it.

For anybody who has a similar issue: 

Nvchad by default disables the plugin `rplugin` in `lua/plugins/configs/lazy_nvim.lua` which offers the command. If you remove it from the list, the command works. 

Thanks for the hint, should have gotten there myself! 🙂
