### ISSUE TITLE
[Bug] `:MoltenSave` does not work with directories that start with `k`

### ISSUE THREAD

**Issue by Kangonaut** [benlubas/molten-nvim#245]
- OS: Ubuntu 22.04
- NeoVim Version: v0.10.0
- Python Version: 3.10.12
- Python is installed with: `venv`
- Health checks

<details>
  <summary>`:checkhealth molten`</summary>

```
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- OK Python module cairosvg found
- OK Python module pnglatex found
- OK Python module plotly found
- OK Python module kaleido found
- OK Python module pyperclip found
- OK Python module nbformat found
- OK Python module pillow found
```

</details>

<details>
  <summary>`:checkhealth provider` (the python parts)</summary>

```
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python3 in the environment.
- Executable: /home/kangonaut/data/purrsonal-id/.venv/bin/python3
- Python version: 3.10.12
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- $VIRTUAL_ENV is set to: /home/kangonaut/data/purrsonal-id/.venv
- Python version: 3.10.12
- OK $VIRTUAL_ENV provides :!python.
```

</details>

## Description

When I use `:MoltenSave` without explicitly specifying my own path, I get the following output: 
```
[Molten] Saved kernel `purrsonal-id` to: /home/kangonaut/.local/share/nvim/molten/%homepurrson
al-idangonaut%data%purrsonal-id%notebooks%example.qmd.json
```
The JSON file is actually stored at the given location, however, the file is named incorrectly.
My Linux username starts with "k", which means that my home directory is `/home/kangonaut`.
This causes problems, since the code replaces `/` in the path with `%` and then continues to replace `%k` with the name of the kernel.
Since the path to my file `/home/kangonaut/path/to/file` is replaced with `%home%kangonaut%path%to%file`, the `%k` in `%kangonaut` is then also replaced by the name of the kernel.
As said, the file is still saved correctly, but the name is wrong, which causes the problem that `MoltenLoad` cannot find the saved JSON file.

Below is the implementation of the `MoltenSave` command:

```python
@pynvim.command("MoltenSave", nargs="*", sync=True)  # type: ignore
@nvimui  # type: ignore
def command_save(self, args) -> None:
    kernels = self._get_current_buf_kernels(True)
    assert kernels is not None

    buf = self.nvim.current.buffer
    if len(args) > 0:
        path = args[0]
    else:
        path = get_default_save_file(self.options, buf)

    if len(args) > 1:
        kernel = args[1]
    else:
        # !!! HERE THINGS GO WRONG !!!
        self.kernel_check(f"MoltenSave {path} %k", buf)
        return

    dirname = os.path.dirname(path)
    if not os.path.exists(dirname):
        os.makedirs(dirname)

    for molten in kernels:
        if molten.kernel_id == kernel:
            with open(path, "w") as file:
                json.dump(save(molten, buf.number), file)
            break
    notify_info(self.nvim, f"Saved kernel `{kernel}` to: {path}")
```

And this is the implementation of the `kernel_check()` function that replaces `%k` with the kernel name:

```python
def kernel_check(self, command: str, buffer: Buffer) -> None:
    """Figure out if there is more than one kernel attached to the given buffer. If there is,
    prompt the user for the kernel name, and run the given command with the new kernel subbed in
    for %k. If there is no kernel, throw an error. If there is one kernel, use it
    """
    self._initialize_if_necessary()

    kernels = self.buffers.get(buffer.number)
    if not kernels and self.options.auto_init_behavior != "raise":
        available_kernels = [(x, False) for x in get_available_kernels()]
        shared_kernels = [(x, True) for x in self.molten_kernels.keys()]
        PROMPT = "You Need to Initialize a Kernel First:"
        self.nvim.lua._prompt_init_and_run(available_kernels + shared_kernels, PROMPT, command)
    elif not kernels:  # and auto_init_behavior == "raise"
        raise MoltenException(
            "Molten is not initialized in this buffer; run `:MoltenInit` to initialize."
        )
    elif len(kernels) == 1:
        c = command.replace("%k", kernels[0].kernel_id)
        self.nvim.command(c)
    else:
        PROMPT = "Please select a kernel:"
        available_kernels = [kernel.kernel_id for kernel in kernels]
        self.nvim.lua._select_and_run(available_kernels, PROMPT, command)
```

## Reproduction Steps

1. create a directory that starts with `k`
2. create a notebook in that directory, initialize molten and try to save the output using `:MoltenSave`
3. the saved JSON file will have the wrong name (aka. the `/k` replaced with the kernel name)

## Workaround (although unsatisfying)

Rename the directory that starts with `k`.

## Expected Behavior

Unfortunately, my proposed _workaround_ is not really an option for me personally, since I cannot rename my home directory.

Looking through the code, it seems like the `kernel_check()` method is used quite a lot, so I can understand if you are hesitant to change its behavior.
But maybe, it would be an option, to just return the name of the kernel from `kernel_check()`, instead of replacing the string in the given command and then executing this command.
This way, the kernel name could first be retrieved and then be embedded into the command string, which would prevent the path string from being touched by `kernel_check()`.

I hope this bug description is sufficient, I've never done this before. :)
Thanks for the amazing plugin!

**Comment by benlubas** [comment]
woah. crazy bug.

Definitely good enough bug report, I know what's going on, I never considered the way kernel check interacts with `%` sign encoding in file paths. Let me look, hopefully it's not a difficult fix

**Comment by benlubas** [comment]
@Kangonaut let me know if using that branch fixes it. And then I'll merge and release

**Comment by Kangonaut** [comment]
Hey, thank you so much for the quick response! Sorry that it took me so long, but I had a problem with nvim-treesitter that took me a while XD. I've tried your fix and it now works flawlessly. Again, thank you so much.

Quick question: Am I supposed to close the issue now, or are you going to do that once you merge the pull request?

**Comment by benlubas** [comment]
GitHub does a cool thing here: because my pr says "fixes #<this issue number>" merging the PR will auto close this issue.
