### ISSUE TITLE
[Bug] Images do not show

### ISSUE THREAD

**Issue by DJPoland** [benlubas/molten-nvim#247]
- OS: M3 Max Sonoma 14.1
- NeoVim Version: v0.10.0
- Python Version: 3.12
- Python is installed with: Create new virtualenv with venv
- Health checks

<details>
  <summary>`:checkhealth molten`</summary>

molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- OK Python module cairosvg found
- OK Python module pnglatex found
- OK Python module plotly found
- OK Python module kaleido found
- OK Python module pyperclip found
- OK Python module nbformat found
- OK Python module pillow found

</details>

<details>
  <summary>`:checkhealth provider` (the python parts)</summary>

provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "~/.virtualenvs/neovim/bin/python3"
- Executable: ~/.virtualenvs/neovim/bin/python3
- Python version: 3.12.7
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- $VIRTUAL_ENV is set to: ~/Code Development/test-jupyter/venv
- Python version: 3.12.7
- OK $VIRTUAL_ENV provides :!python.

</details>

## Description
I have tried to get images to show with molten for quite some time now. Whenever I use matplotlib with everything installed properly based on the directions, I get the following output:

![Screenshot 2024-10-03 at 7 47 11 PM](https://github.com/user-attachments/assets/39f4ad4e-9235-4168-ac33-5fb8d65708ce)

## Reproduction Steps

Follow all instructions from: https://github.com/benlubas/molten-nvim/blob/main/docs/Not-So-Quick-Start-Guide.md

Run `MoltenEvaluateVisual` on all lines. All code being ran can be found in screenshot above.

## Expected Behavior
Image should be appearing after ```plt.show()```

**Comment by DJPoland** [comment]
Ah, do we have to use the kitty terminal instead of iterm2? When I run the code above, images work in kitty.

**Comment by benlubas** [comment]
You you can't use iterm2.

iterm2 doesn't support kitty graphics, which is what image.nvim uses by default (and recommends). and molten uses image.nvim to display it's images.

There are very few terminals that support it.
