### ISSUE TITLE
[Feature Request] Offer to install/add kernel for project when none found for MoltenInit

### ISSUE THREAD

**Issue by paulhersch** [benlubas/molten-nvim#259]
Hi :),

As the title says, i think it would be cool to have a popup (`vim.ui.select`?) asking you, whether you want to create a kernel for a project you are in (similar to how you are asked to choose a kernel for `:MoltenEvaluate<cmd>`) as soon as `MoltenInit` is run on a file.

My (personal) Pro/Con List:

Pro:
  - improved usability for new users
  - raised awareness, that you need to install kernels (I just tried using molten for the first time and needed to understand how the kernel stuff works first)
  - QOL if you share projects between devices and don't sync the kernel spec stuff
 
Con:
  - Would assume you want to create a kernel
  - How to handle different kernel types? (python3, R, julia, ...; might get a little hacky/complicated based on ft)
  - Maybe question/explanation for why this popup happens is too long for the space that is available in smth like telescope.ui.select
  - maintenance overhead(?) (Haven't checked your code yet, but it might just be a "open select if nothing available" thing, but ig a feature like this will eventually mutate into a kernel management tool which might be better served by a seperate plugin(?))

If you don't completely hate the idea of adding that functionality to `:MoltenInit`, i could try putting something together soon:tm:. But as a more general kernel management tool i could try to do that in a different plugin (like mason.nvim does that for LSPs), if you feel like it wouldn't be a good fit/maintainable in molten-nvim.

Thank you for reading and have a nice day!

**Comment by benlubas** [comment]
Yeah I'll be honest I don't want to maintain that. I'm firmly in the camp of "installation of stuff like that should never be handled by a text editor plugin". A system package manager or project management tool like direnv + nix is the way to install stuff like that.

You could create a separate plugin similar to mason to do that though. I'd link to it in the README if you do, just open an issue to let me know. Or at me on this one, I should see it.
