### ISSUE TITLE
[Feature Request] Text-Objects for jupytext "py:percent" format

### ISSUE THREAD

**Issue by S1M0N38** [benlubas/molten-nvim#260]
[Jupytext](https://jupytext.readthedocs.io/en/latest/index.html) is a versatile tool for converting between Jupyter notebooks (`.ipynb`) and Python scripts (`.py`) and vice versa. It provides support for various formats, including the ["percent" format](https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-percent-format), which adds notebook cell metadata as comments in Python scripts.

It would be useful if `molten.nvim` included a custom text object to represent Jupyter notebook cells in Python scripts using this "percent" format. 

#### Use Case

For example, consider the following Python script converted from a Jupyter notebook with three cells:

```python
# %% [markdown]         # ┓
# This is a multiline.  # ┠ first cell (markdown type)
# Markdown cell         # ┃
                        # ┛
# %% [markdown]         # ┓
# Another Markdown cell # ┠ second cell (markdown type)
                        # ┃
                        # ┛
# %%                    # ┓
# This is a code cell   # ┠ third cell (code type)
class A():              # ┃ 
    def one():          # ┃
        return 1        # ┃
                        # ┃ 
    def two():          # ┃
        return 2        # ┛
```

The custom text object would identify and operate on these cell structures. This would allow users to:

1. Navigate between Jupyter cells easily (e.g., move to the next/previous cell).
2. Evaluate cells individually or sequentially using `MoltenEvaluateOperator`.
3. Bind familiar key mappings like `Shift-Enter` or `Ctrl-Enter` to run the current Jupyter cell and move to the next one, emulating the experience of running cells in a Jupyter notebook.

#### Proposed Solution

- Implement a custom text object to recognize Jupyter cells in Python scripts using the "percent" format. 
- Add support for evaluating these cells through `MoltenEvaluateOperator`.
- Optionally, provide default key mappings for running and navigating cells (`Shift-Enter`/`Ctrl-Enter`).

#### Benefits

This feature would enhance the experience of working with Python scripts derived from Jupyter notebooks.

**Comment by benlubas** [comment]
out of scope of this plugin, but https://github.com/GCBallesteros/NotebookNavigator.nvim already implements this. So you can use that.
