### ISSUE TITLE
[Bug] Molten Could not initialize kernel

### ISSUE THREAD

**Issue by mindeng** [benlubas/molten-nvim#264]
- OS: macOS
- NeoVim Version: v0.10.2
- Python Version: python3.13.1
- Python is installed with: brew
- Health checks

<details>
  <summary>`:checkhealth molten`</summary>

==============================================================================
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- OK Python module cairosvg found
- OK Python module pnglatex found
- OK Python module plotly found
- OK Python module kaleido found
- OK Python module pyperclip found
- OK Python module nbformat found
- OK Python module pillow found

</details>

<details>
  <summary>`:checkhealth provider` (the python parts)</summary>

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/Users/dan/.virtualenvs/neovim/bin/python"
- Executable: /Users/dan/.virtualenvs/neovim/bin/python
- Python version: 3.13.1
- pynvim version: 0.5.2
- OK Latest pynvim is installed.

Python virtualenv ~
- $VIRTUAL_ENV is set to: /Users/dan/Library/Caches/pypoetry/virtualenvs/ml-NbjWgKXH-py3.12
- Python version: 3.12.8
- OK $VIRTUAL_ENV provides :!python.

</details>

<details>
<summary>`:MoltenInfo`</summary>
 Molten Info
 Initialized: true

 1 inactive kernel(s):

 Kernel: ml-hello 
   language:     python
   cmd:          /Users/dan/Library/Caches/pypoetry/virtualenvs/ml-NbjWgKXH-py3.12/bin/python -Xfrozen_modules=off -m ipykernel_launcher -f {connection_file}
   resource_dir: /Users/dan/Library/Jupyter/kernels/ml-hello
</details>

## Description

The following error occurs when call `:MoltenInit ml-hello`

```
[Molten] Could not initialize kernel named 'ml-hello'.
Caused By: [Errno 2] No such file or directory: '/Users/dan/Library/Jupyter/runtime/kernel-86a11199-2ce0-41ac-a4e8-73740ac8f358.json'
```

**Comment by benlubas** [comment]
3.13 woah is that released yet? 

Probably not the issue though.  Can you send the output of `jupyter --paths` (think that's the command anyway, I'm on my phone so can't check)

**Comment by mindeng** [comment]
❯ jupyter --paths

```
config:
    /Users/dan/.jupyter
    /Users/dan/Library/Caches/pypoetry/virtualenvs/ml-NbjWgKXH-py3.12/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/dan/Library/Jupyter
    /Users/dan/Library/Caches/pypoetry/virtualenvs/ml-NbjWgKXH-py3.12/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/dan/Library/Jupyter/runtime
```

**Comment by benlubas** [comment]
does that runtime folder actually exist?

**Comment by mindeng** [comment]
> does that runtime folder actually exist?

❯ tree ~/Library/Jupyter/

```
/Users/dan/Library/Jupyter/
└── kernels
    └── ml-hello
        ├── kernel.json
        ├── logo-32x32.png
        ├── logo-64x64.png
        └── logo-svg.svg

3 directories, 4 files
```

The runtime folder doesn't exist. Do you know how to fix this issue? I just follow the doc [Virtual-Environments.md](https://github.com/benlubas/molten-nvim/blob/main/docs/Virtual-Environments.md) to setup the virtual environment.

Thank you for your reply!

**Comment by benlubas** [comment]
you can try just creating the runtime folder manually

I'm not sure why that happens, but some version of jupyter doesn't do it, there was some similar issue a while ago, someone running arch iirc

**Comment by mindeng** [comment]
> you can try just creating the runtime folder manually
> 
> I'm not sure why that happens, but some version of jupyter doesn't do it, there was some similar issue a while ago, someone running arch iirc

It works! Thank you very much!

**Comment by bassamsdata** [comment]
Thank you all. I encountered the same issue on my Mac while installing Python and Jupyter using the `uv` package manager. Manually creating the directory `runtime` resolved the problem.
