### ISSUE TITLE
[Bug] Jupyter Notebook not recognized and detected as json

### ISSUE THREAD

**Issue by Budulman** [benlubas/molten-nvim#265]
When I open an `.ipynb` file, I see a raw json content. `:set filetype?` says `filetype=json`.
I can run `MoltenInit` and attach to running kernel, but none of the commands work.  

- OS: MacOS
- NeoVim Version: NVIM v0.10.1
- Python Version: 3.11.9
- Python is installed with: conda
- Health checks

<details>
  <summary>`:checkhealth molten`</summary>

```
==============================================================================
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python module pynvim found
- OK Python module jupyter-client found
- WARNING Optional python module cairosvg not found
  - ADVICE:
    - pip install cairosvg
- WARNING Optional python module pnglatex not found
  - ADVICE:
    - pip install pnglatex
- WARNING Optional python module plotly not found
  - ADVICE:
    - pip install plotly
- WARNING Optional python module kaleido not found
  - ADVICE:
    - pip install kaleido
- WARNING Optional python module pyperclip not found
  - ADVICE:
    - pip install pyperclip
- OK Python module nbformat found
- OK Python module pillow found

```

</details>

<details>
  <summary>`:checkhealth provider` (the python parts)</summary>
```

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- pyenv: Path: /opt/homebrew/Cellar/pyenv/2.4.19/libexec/pyenv
- pyenv: Root: /Users/budulman/.pyenv
- Using: g:python3_host_prog = "python3"
- Executable: /Users/budulman/anaconda3/envs/lqa311/bin/python3
- Python version: 3.11.9
- pynvim version: 0.5.2
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

```
</details>

## Description
The `.ipynb` file is opened as a standard JSON and although I can successfully run `:MoltenInit`, that's about all I can do with molten.

## Reproduction Steps
Open any `.ipynb` file.

## Expected Behavior
Formatted Jupyter notebook appears and calling commands like `:MoltenEvaluateLine` run the execution.

**Comment by benlubas** [comment]
well yeah. Molten doesn't convert jupyter notebook files to plain text

You can use https://github.com/GCBallesteros/jupytext.nvim for that
