### ISSUE TITLE
[Bug] Molten does not detect python packages installed in local venv

### ISSUE THREAD

**Issue by AnduAriton** [benlubas/molten-nvim#266]
* activate the venv
* open py file in lunar vim ( or lazy vim )
* from command line it runs normaly
* molten yields error: package ... not found

**Comment by AnduAriton** [comment]
Solved by installing packages with %pip install ... directly inside jupyter notebook

**Comment by benlubas** [comment]
The kernel uses packages that are in the venv the kernel was installed from. 

If you install ipython in a venv. It will not have access to the packages in another random venv.
