### ISSUE TITLE
[Feature Request] Export outputs to .ipynb files

### ISSUE THREAD

**Issue by benlubas** [benlubas/molten-nvim#32]
Currently, a large pain point of using molten + some tool to convert Jupyter notebooks to plaintext is the inability to save output from molten in a shareable format (ie. .ipynb).

### Proposed solution to this:
The `:MoltenExport` command.

This would work in a similar way to `:MoltenSave`, but it would look for an existing ipynb file that matches the name of the currently open file and alters it (or maybe makes a copy), so that it contains the output stored by molten.

### concerns
I have many.

- does the Jupyter file format change? are there multiple versions? How often do they change if at all?
- **How do we match up different cells? We could match the code but then different code cells containing the same code could be confused.**
- How can we make this conversion tool agnostic? I'd like this to work with jupytext and quarto documents. They both store information about cells differently, and I don't really want to have to parse these out.
	- comments will probably have to be ignored b/c quarto uses them for metadata
- This is probably going to be a fragile feature, I should definitely make that clear.
- can we save mimetypes that molten doesn't actually display? If I get an HTML output, ideally it could be saved despite not being rendered.

### addressing concerns
Now that I've done some reading

- Yes, there are multiple versions. If we just rely on nbformat, I think this issue more or less goes away.
- This is the hardest part probably. I'm pretty sure that simply using the code cell position in conjunction with the code content will work in all or nearly all cases.
- I'm sure this is something that will be tweaked as more people start to use it
- agree
- yeah this is possible, on the surface it seems like it might be very simple b/c we already save everything.

**Comment by SigmaRichards** [comment]
This would be awesome. I can't offer a lot, but as far as matching cells goes, could potentially just rely on using markdown. Use code-blocks to define cells and the space between code blocks to define markdown-cells.

**Comment by benlubas** [comment]
@SigmaRichards Ideally this should work without relying on the file format. There are many ways that people convert `ipynb` to plaintext. The most common are Quarto and Jupytext. Quarto converts to a markdown-esque format. Jupytext can convert to either a `.py` file with comments delimiting cells, or a plain markdown file.

There are also other ways that people create notebook-like files, neorg and NotebookNavigator.nvim off the top of my head, both of those delimit cells in different ways.

I'd like for all of these methods to work with this command.

I also want to make clear that this wouldn't be converting markdown to `ipynb`, which is a solved problem as far as I'm concerned. This would just be a way to add the outputs from molten to an existing, corresponding, `ipynb` file.

**Comment by benlubas** [comment]
I'm also like 85% sure that just relying on the cell order in the file (in addition to the code content) will be enough to not confuse different cells

**Comment by benlubas** [comment]
@SigmaRichards feel free to checkout that PR, it's in a working state rn. simple instructions for testing: take a jupyter notebook file, convert it to a plaintext format however you want (make sure they have the same name, ie. test.ipynb and test.qmd) and then open the plaintext doc, run code with molten, and run `:MoltenExport`.

You can then open a copy of the notebook file that was produced in jupyter-lab and see the output from the code you ran.

Keep in mind that things might break and I haven't extensively tested yet, if you find issues you can leave them here and I can be sure to iron them out!
