### ISSUE TITLE
[Bug] `:UpdateRemotePlugins` failing, not an editor command

### ISSUE THREAD

**Issue by chrisgrieser** [benlubas/molten-nvim#49]
- OS: macOS 13.6.1 (M1)
- NeoVim Version: 
```
- NVIM v0.9.2
- Build type: Release
- LuaJIT 2.1.0-beta3
```

## Description
Running `:UpdateRemotePlugins` results in the error message `E492: Not an editor command: UpdateRemotePlugins`, even though all requirements are installed correctly.

## Reproduction Steps
- Install molten via lazy by adding `{ "benlubas/molten-nvim" }`
- shut down nvim
- activate virtual environment in a project
- `pip install ipykernel jupyter pynvim`
- start nvim
- run `:UpdateRemotePlugins`

## Expected Behavior
`:UpdateRemotePlugins` should work

---

Context: This is the output of `checkhealth`:
```
Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/Users/chrisgrieser/repos/axelrod-prisoner-dilemma/.venv/bin/python"
- Executable: /Users/chrisgrieser/repos/axelrod-prisoner-dilemma/.venv/bin/python
- Python version: 3.11.6
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- $VIRTUAL_ENV is set to: /Users/chrisgrieser/repos/axelrod-prisoner-dilemma/.venv
- Python version: 3.11.6
- OK $VIRTUAL_ENV provides :!python.
```

**Comment by benlubas** [comment]
I'm very confused by this. I have an M2 mac and when I run 0.9.2 it works for me. Your checkhealth stuff looks correct to me.

Something you could try is adding `build = ":UpdateRemotePlugins",` to the lazy spec. I'm not sure why that would work, but it's easy to try.

I was under the impression that `:UpdateRemotePlugins` was a builtin command. If I run `nvim --clean` I see that it exists, and running it produces a different error, suggesting that it does exist.

How do you have neovim installed?

**Comment by chrisgrieser** [comment]
ah, yes, it also works when using `nvim --clean`.

And I actually figured it out. I have `rplugin` in my disabled plugins in the `lazy.nvim` config. 🤦‍♂️ 

Just copypasted a list of stuff to disable a while ago. Removing it from the list of disabled plugins fixes it.
