### ISSUE TITLE
[Bug] Displayed images don't respond to adding/removing lines

### ISSUE THREAD

**Issue by benlubas** [benlubas/molten-nvim#50]
## Description
When you have an image shown as a virtual output, adding or removing a newline above or below the image knocks it out of place, the only way to get it back is by re-running the cell or restoring the lines back to how they were before.

There is a similar issue with open output windows that could be solved at the same time.

## Reproduction Steps
run a cell with image output
add a line above it

## Expected Behavior
Image positions should update when new lines are added or removed. This is probably a use case for change tick, and I can just run it in the molten tick function. I'm not sure.

**Comment by benlubas** [comment]
I think this is an issue with image.nvim

**Comment by Bekaboo** [comment]
Also come across this problem. However I don't think it is image.nvim's bug, because in markdown files images always get updated correctly when text changes.

**Comment by benlubas** [comment]
Here's the related image.nvim issue: https://github.com/3rd/image.nvim/issues/83

I'm not seeing that the document integration updates the image position (using the master branch of image.nvim), but it seems to work for everyone else. I must have a plugin that's interfering.

Either way, I'm of the opinion that images sticking to their extmarks should be something the image.nvim library implements as a part of it's API. I just think that logic fits more nicely in the plugin which manages images for neovim.

That said I will eventually look into a workaround/rip the repositioning code from image.nvim and use it here. (or accept a PR that implements this logic in a contained place that's easy to remove should image.nvim update in the future).

I think that image.nvim has an overhaul in the works, though I'm not sure. I reached out to the maintainer to see what that looks like currently.

**Comment by benlubas** [comment]
@Bekaboo latest image.nvim adds support for sticking images to their extmarks.

There were a few problems with it, but I think they're ironed out. I haven't had problems in my limited testing but as always feel free to open a new issue if you find any

**Comment by Bekaboo** [comment]
@benlubas Thanks for letting me know the good news! I will test it when I get time :+1:
