### ISSUE TITLE
[Feature Request] Add command for running current code block / code blocks above / code blocks below

### ISSUE THREAD

**Issue by Bekaboo** [benlubas/molten-nvim#58]
Hi, thanks for making this plugin, it is a huge addition to my jupyter notebook workflow.

Being able to evaluate the current code block quickly is an essential part of a fluent experience with jupyter notebook, but there's no easy way to do this with molten-nvim.

Currently, we have to select the code block manually and call `:MoltenEvaluateVisual`, which feels clunky. I tried the setup using treesitter text object introduced in https://github.com/benlubas/molten-nvim/blob/main/docs/Notebook-Setup.md#jupytext, but it only select a python block instead of the whole block in the markdown file:

![image](https://github.com/benlubas/molten-nvim/assets/76579810/25bb403d-c129-4ef9-ac30-77d9a7df3842)

What is hope to achieve is:

1. Pressing `<CR>` (without selection) inside a python code block will run that code block through jupyter kernel
2. Selecting a region in code block and then pressing `<CR>` will run the selected code only, this is already possible using `:MoltenEvaluateVisual`
3. `<CR>` mapping should be buffer-local, i.e. only set for buffers that have molten attached
4. Add other commands that runs all code blocks above / below the current block, like what we can do in jupyter lab or vscode

**Comment by benlubas** [comment]
This is out of the scope of Molten b/c there are different ways that people work with notebooks. The good news is that the markdown code cell integration is solved with [quarto-nvim](https://github.com/quarto-dev/quarto-nvim), all the functionality you've described is implemented.

It looks like you're using a plugin that might not convert to markdown though, is it [jupyter-vim](https://github.com/jupyter-vim/jupyter-vim)? could you clarify what plugin you're using?

@Bekaboo

**Comment by Bekaboo** [comment]
Hi thanks for your reply, I am using jupytext.vim and shown in the screenshot is the converted markdown file. I am currently using otter.nvim, jupytext.nvim and headlines.nvim. The only thing I feel missing is the ability to run current code block or code blocks above/below.

I tried to use quarto-nvim but never got it work for me, it even makes otter.nvim's suggestion disappeared which I suspect is due to the fact that quarto-nvim uses otter.nvim under the hood and the setup function is called twice. I do not work with qmd files so I wonder why I will need it, and if I do, how can I set it up for markdown files (tried to call `:QuartoActivate` in md files, nothing happens, except that it makes my otter.nvim suggestions disappear)

**Comment by benlubas** [comment]
Quarto now has an [integration](https://github.com/quarto-dev/quarto-nvim#running-code) with Molten to run code cells in the way that you described. You are right in that if you use quarto-nvim you shouldn't also setup otter on your own, it should handle that for you.

Curious that the `:QuartoActivate` command doesn't work for you. I wonder if that has to do with how you're also setting up otter yourself? It could cause trouble.

If you comment out your otter config does it still cause problems? You might also want to try in a `.qmd` document as well just to know that the quarto-nvim plugin is working at least for those.

Once you get the `:QuartoActivate` command to work manually you can setup a markdown filetype plugin that will run the command for you automatically when you open a markdown buffer.
