### ISSUE TITLE
[Help] How to deal with outputs

### ISSUE THREAD

**Issue by Bekaboo** [benlubas/molten-nvim#59]
Hi, thanks for developing molten -- it is a great plugin. I have been playing with molten recently, but cannot find a good way to interact with the outputs, mainly:

1. Cannot copy text from output. Seems that outputs are shown in a unfocusable floating window, so `<C-w><C-w>` does not bring me to that window, and every time I move my cursor near the window, it disappears.
2. Cannot save images from output.
3. If the code block is higher than my screen, I have to scroll to the end to see the outputs, and I have to be careful because if I scroll over the block, the output window will disappear and I have to `:MoltenShowOutput` to see it.
4. Ouputs are not displayed like what is shown in the demo video in README, instead they are shown in floating windows. I prefer the output style in the demo video, how can I achieve that?

I have looked through the doc of magma and molten but failed to find a solution to the problems above. Could you help me figure out a solution?

---

EDIT: I discovered `:MoltenEnterOutput`, which can (partly) answer the first question, but get this error when I run this command:

![image](https://github.com/benlubas/molten-nvim/assets/76579810/b0d4e32f-ffcf-4833-97f0-db14bef47e87)

The output window is already shown when I run `:MoltenEnterOutput`

Also it would be greate if molten expose a function like `molten_output_visible()`, so that user can use the same keybinding to show and enter the output, somewhat like how `K` works for LSP hover window:

```lua
local function open_or_enter_output()
    if molten_output_visible() then
        molten_output_enter()
    else
        molten_output_open()
    end
end
```

**Comment by benlubas** [comment]
You can find answers to most of your questions in the readme. 

1. Copying text is done by entering the output window. 

2. Saving images that you produce would best be done in code. There's currently no way to save them. That's a good feature request tho. It's totally doable.

3. Yeah this is done so the output window doesn't cover any code you ran. I've also noticed this is inconvenient sometimes and have considered making the show output command scroll so the output is on screen it it wouldn't already be on screen. You can also open a feature request issue for this.

4. Take a look at the table in the readme with all the config variables, out of them is like `molten_virt_text_output` that'll get you output like in the demo. This is not the default for compatibility. I didn't want to break existing users. 

As for the double mapping to both show and enter the output window. There's an example of this key binding in the readme. The command `:MoltenEnterOutput` needs to be called like this: `:noautocmd MoltenEnterOutput` and by default this command behaves the way you want, it opens the window if it's not open, and enters the window if its already open.

**Comment by Bekaboo** [comment]
@benlubas Thanks for your reply! Setting `vim.g.molten_virt_text_output` solves problem 4, but now I cannot use `:MoltenEnterOutput` to copy the output text. Is there any workaround for this?

**Comment by benlubas** [comment]
Yeah, you can still open the output window with `:noautocmd MoltenEnterOutput` (when you're in a code cell) and then run that command again to enter the output. Once you're in the output window copy like normal.

**Comment by Bekaboo** [comment]
Ah, that makes sense. Thanks for answer my silly questions! Closing as completed.

**Comment by monkeyxite** [comment]
> Hi, thanks for developing molten -- it is a great plugin. I have been playing with molten recently, but cannot find a good way to interact with the outputs, mainly:
> 
> 1. Cannot copy text from output. Seems that outputs are shown in a unfocusable floating window, so `<C-w><C-w>` does not bring me to that window, and every time I move my cursor near the window, it disappears.
> 2. Cannot save images from output.
> 3. If the code block is higher than my screen, I have to scroll to the end to see the outputs, and I have to be careful because if I scroll over the block, the output window will disappear and I have to `:MoltenShowOutput` to see it.
> 4. Ouputs are not displayed like what is shown in the demo video in README, instead they are shown in floating windows. I prefer the output style in the demo video, how can I achieve that?
> 
> I have looked through the doc of magma and molten but failed to find a solution to the problems above. Could you help me figure out a solution?
> 
> EDIT: I discovered `:MoltenEnterOutput`, which can (partly) answer the first question, but get this error when I run this command:
> 
> ![image](https://private-user-images.githubusercontent.com/76579810/285825839-b0d4e32f-ffcf-4833-97f0-db14bef47e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTE0NTcsIm5iZiI6MTcxMjI5MTE1NywicGF0aCI6Ii83NjU3OTgxMC8yODU4MjU4MzktYjBkNGUzMmYtZmZjZi00ODMzLTk3ZjAtZGIxNGJlZjQ3ZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA0MjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmM0NmVlMmUyZTZhZWFiMDE0ODdlMDZjZjU0OWZlYThhMTdmMWE5OGFjOWUzZWQxN2M1MGViMDA0Njk2NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lYP1Bp9I0FTKahxHSjxX7U8kP1_Xf3AWLX-gkI6Ss_s)
> 
> The output window is already shown when I run `:MoltenEnterOutput`
> 
> Also it would be greate if molten expose a function like `molten_output_visible()`, so that user can use the same keybinding to show and enter the output, somewhat like how `K` works for LSP hover window:
> 
> ```lua
> local function open_or_enter_output()
>     if molten_output_visible() then
>         molten_output_enter()
>     else
>         molten_output_open()
>     end
> end
> ```

@Bekaboo , how did you deal with the error in the EDIT? I could not simply clear the error here.

**Comment by benlubas** [comment]
@monkeyxite he read the readme. 

You need to run molten enter output with noaucmd or noautocmd or whatever it is (I'm tired just check the readme).

**Comment by monkeyxite** [comment]
@benlubas Oh, indeed. 
Keybinded with noautocmd but when testing forget to pre-fix that...

Thanks for the hints and informative question and answer here.
