### ISSUE TITLE
Commands not showing up after installng the plugin.

### ISSUE THREAD

**Issue by leet0rz** [benlubas/molten-nvim#60]
- OS: Windows
- NeoVim Version: 0.10.0

## Description
[Commands not showing up](https://i.imgur.com/j55aBvN.png)

## Reproduction Steps
I just installed it with lazy neovim and that's it. It shows as loaded and installed, but commands not showing up.

## Expected Behavior
For the commands to work and show up after `:`

**Comment by benlubas** [comment]
Can you share your config? Or a minimal reproduction of the issue?

And I just want to make sure that `:UpdateRemotePlugins` is producing output that looks similar to this: 
<img width="796" alt="image" src="https://github.com/benlubas/molten-nvim/assets/56943754/c81c6ea3-854a-40c5-a636-cd833d50a2d6">

@leet0rz

**Comment by leet0rz** [comment]
> UpdateRemotePlugins


```
function remote#host#UpdateRemotePlugins[6]..<SNR>42_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5
Plugin "C:/Users/waffle/AppData/Local/nvim-data/lazy/molten-nvim/rplugin/python3/molten" is already registered
remote/host: generated rplugin manifest: C:\Users\waffle\AppData\Local\nvim-data/rplugin.vim               
```

**Comment by benlubas** [comment]
@leet0rz can you open the `C:\Users\waffle\AppData\Local\nvim-data/rplugin.vim` file and see what it's contents are?

**Comment by leet0rz** [comment]
> @leet0rz can you open the `C:\Users\waffle\AppData\Local\nvim-data/rplugin.vim` file and see what it's contents are?

```
" perl plugins


" node plugins


" ruby plugins


" python plugins

```

**Comment by benlubas** [comment]
Hmmm. That file should have all the molten commands in it. Unfortunately I don't have windows to test on, but it could be a number of things. Here's what I'd do:

- try on nvim 9.4 which is the latest stable
- if you have WSL or another (non windows) device to test on, try that and see what happens, windows is weird sometimes
- try to create a minimal config (ie. just one file with only the molten plugin and nothing else) and see if it still doesn't work

**Comment by leet0rz** [comment]
> Hmmm. That file should have all the molten commands in it. Unfortunately I don't have windows to test on, but it could be a number of things. Here's what I'd do:
> 
>     * try on nvim 9.4 which is the latest stable
> 
>     * if you have WSL or another (non windows) device to test on, try that and see what happens, windows is weird sometimes
> 
>     * try to create a minimal config (ie. just one file with only the molten plugin and nothing else) and see if it still doesn't work



I am on nightly right now, so the very newest version. Same thing happened for 9.4.

I tried to run lazy + molten and here is the result after running the update command:


```
function remote#host#UpdateRemotePlugins[6]..<SNR>26_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[12]..provider#Poll, line 7
Vim(if):Error invoking 'poll' on channel 3:^@Invalid channel: 3
Traceback (most recent call last):^M
  File "<string>", line 1, in <module>^M
  File "C:\Users\waffle\AppData\Local\Programs\Python\Python312\Lib\site-packages\neovim\__init__.py", line 5, in <module>^M
    import pynvim^M
  File "C:\Users\waffle\AppData\Local\Programs\Python\Python312\Lib\site-packages\pynvim\__init__.py", line 9, in <module>^M
    from pynvim.api import Nvim, NvimError^M
  File "C:\Users\waffle\AppData\Local\Programs\Python\Python312\Lib\site-packages\pynvim\api\__init__.py", line 7, in <module>^M
    from pynvim.api.buffer import Buffer^M
  File "C:\Users\waffle\AppData\Local\Programs\Python\Python312\Lib\site-packages\pynvim\api\buffer.py", line 2, in <module>^M
    from pynvim.api.common import Remote^M
  File "C:\Users\waffle\AppData\Local\Programs\Python\Python312\Lib\site-packages\pynvim\api\common.py", line 6, in <module>^M
    from pynvim.compat import unicode_errors_default^M
  File "C:\Users\waffle\AppData\Local\Programs\Python\Python312\Lib\site-packages\pynvim\compat.py", line 5, in <module>^M
    from imp import find_module as original_find_module^M
ModuleNotFoundError: No module named 'imp'^M
function remote#host#UpdateRemotePlugins[6]..<SNR>26_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require[12]..provider#Poll, line 17
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
remote/host: generated rplugin manifest: C:\Users\waffle\AppData\Local\nvim-data/rplugin.vim 
```

I tried to open the rplugin.vim file and it still looks the same as before.

I am on the latest python release which a lot of stuff have not caught up yet. Maybe your plugin does not work with the newest version of python? Just an idea as I know many others had to redo some stuff to get their libs to work with python 3.12

**Comment by benlubas** [comment]
Try using the master branch of pynvim, that issue has been fixed but not released. 

related issue: https://github.com/neovim/pynvim/issues/538#issuecomment-1760735880

The error that you're seeing is probably related to not having a python3 host program specified in your minimal config. see `:h g:python3_host_prog`

**Comment by leet0rz** [comment]
> Try using the master branch of pynvim, that issue has been fixed but not released.
> 
> related issue: [neovim/pynvim#538 (comment)](https://github.com/neovim/pynvim/issues/538#issuecomment-1760735880)
> 
> The error that you're seeing is probably related to not having a python3 host program specified in your minimal config. see `:h g:python3_host_prog`

Added, the errors went away and I managed to define the path for python via `vim.g.python3_host_prog = 'C:\\Users\\waffle\\AppData\\Local\\Programs\\Python\\Python312\\python.exe'
`

When I run the update command this shows:

```
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: C:\Users\waffle\AppData\Local\nvim-data/rplugin.vim
```

Still no command though.

**Comment by benlubas** [comment]
Can you look at the output of `:checkhealth`? There's a section for molten, make sure that's fine, but I'm more interested in the section that mentions pynvim. Could you include that output?

Also could you share your minimal config so I can test it out.

Also also if you have time, I'd be curious 5o see what happens when trying to run this with python 3.11

**Comment by leet0rz** [comment]
Config:

```
vim.g.mapleader = " "
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "benlubas/molten-nvim",
        version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
        build = ":UpdateRemotePlugins",
        init = function()
            -- these are examples, not defaults. Please see the readme
            vim.g.molten_output_win_max_height = 20
            vim.g.molten_auto_open_output = false
        end,
    },
})
```

health check:
```
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- ERROR Failed to run healthcheck for "molten" plugin. Exception:
  function provider#python3#Call, line 18: Vim(return):Error invoking 'python_eval' on channel 6 (python3-script-host):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  AttributeError: module 'importlib' has no attribute 'util'
```

**Comment by benlubas** [comment]
Oh that's awkward. Molten's healthcheck doesn't run on python versions greater than 3.10.something b/c import lib changed... 

I see that too but my plugin is working. What's the output from `:checkhealth provider`? specifically the python parts

**Comment by benlubas** [comment]
I just merged a fix for that healthcheck issue. If you want to try with the latest version of main, you should see your healthcheck work

**Comment by leet0rz** [comment]
Output from checkhealth provider:
```
Python 3 provider (optional) ~
- Using: g:python3_host_prog = "C:\Users\waffle\AppData\Local\Programs\Python\Python312\python.exe"
- Executable: C:\Users\waffle\AppData\Local\Programs\Python\Python312\python.exe
- Python version: 3.12.0
- pynvim version: 0.5.0dev0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV
```

I updated via Lazy to the latest molten but it still outputs this on checkhealth:
```
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- ERROR Failed to run healthcheck for "molten" plugin. Exception:
  function provider#python3#Call, line 18: Vim(return):Error invoking 'python_eval' on channel 7 (python3-script-host):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  AttributeError: module 'importlib' has no attribute 'util'
  ```

**Comment by benlubas** [comment]
do you still have `version = "^1.0.0"`? You should remove this to use the main branch of the plugin b/c I haven't created a new release yet.

**Comment by leet0rz** [comment]
> do you still have `version = "^1.0.0"`? You should remove this to use the main branch of the plugin b/c I haven't created a new release yet.

Removed that part and now the checkhealth is a bit different:
```
molten: require("molten.health").check()

molten-nvim ~
- OK NeoVim >=0.9
- OK Python >=3.10
- OK Python package pynvim found
- OK Python package jupyter-client found
- WARNING Python package cairosvg not found
  - ADVICE:
    - pip install cairosvg
- WARNING Python package pnglatex not found
  - ADVICE:
    - pip install pnglatex
- WARNING Python package plotly not found
  - ADVICE:
    - pip install plotly
- WARNING Python package kaleido not found
  - ADVICE:
    - pip install kaleido
- WARNING Python package pyperclip not found
  - ADVICE:
    - pip install pyperclip
```

rplugin still empty and no Molten command yet.

**Comment by benlubas** [comment]
I'm very confused at this point, maybe python 3.12 is causing problems, or windows. If you want to change either of those and test it might help figure out what's happening.

A potential temporary solution is to just add this to your manifest file and change the path to point to where molten is installed on your system. I'm not 100% sure that will work. But it might.

```vim
call remote#host#RegisterPlugin('python3', '/home/benlubas/github/molten-nvim/rplugin/python3/molten', [
      \ {'sync': v:true, 'name': 'MoltenDeinit', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenDelete', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEnterOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenReevaluateCell', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateLine', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateOperator', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateVisual', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenExportOutput', 'type': 'command', 'opts': {'bang': '', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenGoto', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenHideOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenInfo', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenInit', 'type': 'command', 'opts': {'complete': 'file', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenInterrupt', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenLoad', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenNext', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenPrev', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenRestart', 'type': 'command', 'opts': {'bang': '', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenSave', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenShowOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateArgument', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateRange', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenBufLeave', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenRunningKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenDefineCell', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOperatorfunc', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenTick', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnBufferUnload', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnCursorMoved', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnExitPre', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnWinScrolled', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenStatusLineInit', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenStatusLineKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenUpdateInterface', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenUpdateOption', 'type': 'function', 'opts': {}},
     \ ])
```

**Comment by leet0rz** [comment]
Do I add that anywhere in the rplugin file or a different one?

**Comment by benlubas** [comment]
Yeah, add that to `C:\Users\waffle\AppData\Local\nvim-data/rplugin.vim`

Currently that file is just empty (or rather, has some comments), so it doesn't matter where you add it.

and then change `/home/benlubas/github/molten-nvim/rplugin/python3/molten` to the path that lazy installed the plugin. the ending of your path should look similar (ie. `/molten-nvim/rplugin/python3/molten` but with windows path separators) b/c that file structure is a part of the plugin.

I'll stress that if this works it's a temporary solution and would break if the plugin gets a new command for example. You should still try to figure out why your remote plugins aren't working.

**Comment by leet0rz** [comment]
Commands show up but getting this error when trying to run any command:
```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:                                                                                                                   line    2:
Error invoking '/c/users/waffle/appdata/Local/nvim-data/lazy/molten-nvim/rplugin/python3/molten:command:MoltenInfo' on channel 6 (python3-rplugin-host):
no request handler registered for "/c/users/waffle/appdata/Local/nvim-data/lazy/molten-nvim/rplugin/python3/molten:command:MoltenInfo"     
```

**Comment by benlubas** [comment]
Okay so `:UpdateRemotePlugins` just isn't working at all, it's not just failing to write the manifest file.

At this point I can't help much. I can test on python 3.12, but I can't test on windows. You can try to solve this by either changing the python version that you're using for neovim, or you can try on a different operating system (or WSL).

Either way this isn't a bug with molten, it seems like an issue with neovim and the `:UpdateRemotePlugins` command.

**Comment by leet0rz** [comment]
> Okay so `:UpdateRemotePlugins` just isn't working at all, it's not just failing to write the manifest file.
> 
> At this point I can't help much. I can test on python 3.12, but I can't test on windows. You can try to solve this by either changing the python version that you're using for neovim, or you can try on a different operating system (or WSL).
> 
> Either way this isn't a bug with molten, it seems like an issue with neovim and the `:UpdateRemotePlugins` command.

My guess its a pathing issue since it was developed on linux and not on windows the slashes do not match. Often resolved by fitting the path with "PATH", at least in some cases. Is the plugin required to run as remote plugins? I see a lot of other plugins not run on require and its quite simple, first time running into this issue and I've ran quite a few plugins on windows with no issues.

Thanks for trying anyway. Best of luck.

**Comment by benlubas** [comment]
Yes this absolutely needs to be a remote plugin as it's currently written in python using pynvim. Most neovim plugins are written in lua, which is natively supported by neovim. This plugin is written in python so it can make use of some jupyter libraries (as well as others like nbformat, pnglatex, cariosvg, etc etc).

You can read more about remote plugins and try to figure out if it's a pathing issue in `:h remote-plugin`. If you do happen to figure something out, I'd appreciate an update so I can help others in the future!

**Comment by benlubas** [comment]
@leet0rz Someone on reddit had a [similar issue](https://www.reddit.com/r/neovim/comments/18bymjn/deoplete_on_neovim_094_with_pynvim_050/) with a different plugin and was able to use the method I suggested of copying that manifest file into the correct location. They just had to use `\\\\` as a path separator.

Checkout that post, and hopefully this can get it working temporarily. This seems like a bug in core but I don't have a windows system so I'm not in a position to fix it.

**Comment by leet0rz** [comment]
Thank you. I will mess around with it 👍

**Comment by leet0rz** [comment]
> @leet0rz Someone on reddit had a [similar issue](https://www.reddit.com/r/neovim/comments/18bymjn/deoplete_on_neovim_094_with_pynvim_050/) with a different plugin and was able to use the method I suggested of copying that manifest file into the correct location. They just had to use `\\\\` as a path separator.
> 
> Checkout that post, and hopefully this can get it working temporarily. This seems like a bug in core but I don't have a windows system so I'm not in a position to fix it.

Seems to be working after adding all that text to the rplugin file and making the path with "\\\\" separators at the top. Now I can run :MoltenInit and the Molten run command and have it run the cell. Cool, this is what I have been looking for. I ran into another bug tho:

Had to edit the below because format just shows codebox lol:
3 DOTS{python}
print("Hello World!")
3 DOTS

This runs just fine:
3 DOTS{python}
print("Hello World!")

3 DOTS

This code returns a "invalid syntax error", but if I add a line before the "```" at the end it works. Would be great if you could fix both of these and have windows users be able to use molten without having to do this, hehe. Thanks.

**Comment by benlubas** [comment]
Can you open a new issue for the new problem. In that issue could you include how you're running the code and the complete error message (a screenshot would be fine)?

also, you can display raw code cells inside code cells that are opened with four back ticks like this:
````
```{python}
print("hello world")
```
````

The raw markdown for displaying that looks like:
`````
````
```{python}
print("hello world")
```
````
`````

**Comment by benlubas** [comment]
> Would be great if you could fix both of these and have windows users be able to use molten without having to do this

I'm not a Windows user so it's very hard for me to debug and fix this issue. It it also not a Molten issue, it's either a neovim or pynvim issue.

I do have a windows install now, thanks to a game dev class, so maybe I will get around to it, but someone who actually uses windows is much better suited to fix a bug like this.

**Comment by leet0rz** [comment]
> > Would be great if you could fix both of these and have windows users be able to use molten without having to do this
> 
> I'm not a Windows user so it's very hard for me to debug and fix this issue. It it also not a Molten issue, it's either a neovim or pynvim issue.
> 
> I do have a windows install now, thanks to a game dev class, so maybe I will get around to it, but someone who actually uses windows is much better suited to fix a bug like this.

For me it generated an empty file basically, if you have it overwrite that file and sort it with the correct pathing it should be working. The following file works for me now:
```
"                                            \/ --- This file path
call remote#host#RegisterPlugin('python3', 'C:\\\\Users\\\\waffle\\\\AppData\\\\Local\\\\nvim-data\\\\lazy\\\\molten-nvim\\\\rplugin\\\\python3\\\\molten', [
      \ {'sync': v:true, 'name': 'MoltenDeinit', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenDelete', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEnterOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenReevaluateCell', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateLine', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateOperator', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateVisual', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenExportOutput', 'type': 'command', 'opts': {'bang': '', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenGoto', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenHideOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenImportOutput', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenInfo', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenInit', 'type': 'command', 'opts': {'complete': 'file', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenInterrupt', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenLoad', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenNext', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenOpenInBrowser', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenPrev', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenReevaluateAll', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenRestart', 'type': 'command', 'opts': {'bang': '', 'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenSave', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenShowOutput', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateArgument', 'type': 'command', 'opts': {'nargs': '*'}},
      \ {'sync': v:true, 'name': 'MoltenEvaluateRange', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenAvailableKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenBufLeave', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenRunningKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenDefineCell', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOperatorfunc', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenTick', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnBufferUnload', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnCursorMoved', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnExitPre', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenOnWinScrolled', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenStatusLineInit', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenStatusLineKernels', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenUpdateInterface', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'MoltenUpdateOption', 'type': 'function', 'opts': {}},
     \ ])
```

**Comment by benlubas** [comment]
I can't just overwrite that file, other remote plugins also rely on it, and I don't want to deal with parsing it. Would be better to just get it fixed in Neovim core/pynvim wherever the issue is.
