### ISSUE TITLE
[Feature Request] Smart auto init on first run

### ISSUE THREAD

**Issue by Bekaboo** [benlubas/molten-nvim#61]
Currently, if the user tries to run a molten command without initialization, molten throws an error, but running `:MoltenInit xxx` manually on each file is cumbersome, especially when you have multiple notebooks and Python files opened.

The user experience can be significantly improved if we can ask the user to initialize molten the first time they try to run a command from molten. It should work like the jupyter notebook integration in vscode, where the user will be asked to choose a kernel if they haven't chosen one before running the code.

Additionally, when molten is initialized in a new buffer, it should automatically re-use an existing kernel if there is one attached to an old buffer with the same root directory instead of creating a new one. A root directory can be defined as the first directory that contains `.git/`, `.editorconfig`, or something else, similar to the root detection implemented in nvim-lspconfig. The root patterns should be configurable using a list global value, e.g. `vim.g.molten_root_pattern = { '.git/', '.editorconfig' }`.

Just some thoughts, I have spent hours looking at the code and trying to implement this feature but without success.

**Comment by benlubas** [comment]
While I agree that it's somewhat cumbersome to initialize a kernel multiple times, automatically prompting for initialization is complicated by us not knowing if the user would like to use a shared kernel, or a new one.

So say I want to run `:MoltenEvaluateLine` in a new buffer, the plugin could either:
- prompt for a new kernel to start
- prompt for a shared kernel to use
- let the user know that they need to initialize a kernel

and I like the third option the best.


That said. You can programmatically start kernels. There's a somewhat related example in the [venv docs](https://github.com/benlubas/molten-nvim/blob/main/docs/Virtual-Environments.md#automatically-launch-the-correct-kernel) page.

You could adapt that to automatically attach to kernels using autocommands

**Comment by Bekaboo** [comment]
I like the first + second option: "prompt for a new kernel or existing kernels for a user to choose" and I would like to know if you would accept a PR for it.

**Comment by benlubas** [comment]
Depending on the implementation. It would have to be behind a configuration variable. But it would be a fairly easy thing to implement I think. I'm pretty sure most all the user commands call a function to error check, and that function can just check the config and decide what to do.

**Comment by benlubas** [comment]
@Bekaboo I've thought about this more, and I think simply adding currently running kernels to the list like: `(shared) kernel_name` would work very well, while not forcing the user to cancel the prompt if they want to initialize a shared kernel.

But I think it should still be configurable, and the current behavior will stay the default, just b/c I don't want to change behavior on people when they update.

I also want to let you know that I'll pick this up tomorrow, so we don't end up working on the same thing

**Comment by Bekaboo** [comment]
@benlubas Thanks for letting me know the good news! So you are talking about adding running kernel to the select entries so the user will not have to specify `--shared` in `:MoltenInit`? What about prompting the user to start a kernel on the first run if the kernel has not been initialized?

**Comment by benlubas** [comment]
I'll do both. I don't see any harm in adding running kernels to the bottom of the regular `:MoltenInit` prompt, and it makes sense to do so if we're going to prompt for initialization when a command would otherwise error b/c there aren't any kernels initialized.

> What about prompting the user to start a kernel on the first run if the kernel has not been initialized?

As far as the exact behavior for this new option: if you try to run something like `:MoltenEvaluateRange` in a buffer without any kernels initialized, you will get a prompt as if you had run `:MoltenInit`, and then it will take the kernel that you pass, and run the evaluate range command for that kernel.

**Comment by benlubas** [comment]
#103 does the first part of this

**Comment by benlubas** [comment]
Having the original command execute for the kernel that the user selects is quite challenging, and would require a lot more thinking/rewriting to implement it in a way that I'm happy with.

I think automatically prompting for a kernel to initialize is still a decent improvement over the current behavior of telling you to do it yourself, so I'm still going to implement that. But having commands queued up for after a kernel is started is going to have to wait.

edit: I might just dig in and find a clean solution. I feel like I might as well at this point and I don't have a lot to do right now.
