### ISSUE TITLE
[Help] [Molten] Not in cell

### ISSUE THREAD

**Issue by Mayur1009** [benlubas/molten-nvim#63]
I have a quarto document and some Python cells. Molten is not able to recognize a cell. When using the commands like `:MoltenNext`, `:MoltenPrev`, and `:MoltenReevaluateCell`, it gives an error, `[Molten] Not in cell`. Do I need to set cell delimiters here?

![Screenshot_20231128_221014](https://github.com/benlubas/molten-nvim/assets/31240856/5aaae78b-e41b-4bef-87b3-22f9e29953d4)
![Screenshot_20231128_220939](https://github.com/benlubas/molten-nvim/assets/31240856/b7ae5e21-acb7-4331-9158-663d05e15fa7)
![Screenshot_20231128_221258](https://github.com/benlubas/molten-nvim/assets/31240856/7c375f44-2536-473f-80f1-fd6f760954c4)

**Comment by benlubas** [comment]
The concept of cell in molten is different to the concept of cell in a quarto notebook.

A cell (in molten) is a chunk of code that you've already run. You know that you're in a cell by the highlight when your cursor is in it.

If you highlight your code and run `:MoltenEvaluateVisual` this would create a cell and you can hopefully see what I'm talking about.

Fun easily running code in a quarto doc, I'd recommend making use of the code running integration. and for navigation, I personally use treesitter text objects to get around, and not the molten commands b/c they don't work for quarto cells that haven't been run.

**Comment by Mayur1009** [comment]
Ok, got it. Thanks for the help.
