### ISSUE TITLE
[Feature Request] Automatically define cells

### ISSUE THREAD

**Issue by serhez** [benlubas/molten-nvim#68]
It would be quite useful if cells were defined automatically when loading a file. This should be doable as cells tend to be within well defined blocks of text (e.g., between ``` lines in md or qmd). Then, we could have commands to create and remove cells, which insert these characters and define the cells' range.

What do you think?

**Comment by benlubas** [comment]
Generally I want to keep molten as "just" a code running plugin with as little bias towards notebooks as possible. There are of course some features like this, most notably exporting to `.ipynb` but that's in this plugin b/c it's quite literally the only way to do it. With this suggestion, I feel there are other (better) ways than adding to molten.

With that in mind, I'm definitely open to feedback and thoughts:
What's the advantage to having molten cells defined if the code isn't run?

If you just want to run all the cells, [quarto-nvim](https://github.com/quarto-dev/quarto-nvim) is the way I do that. 

As for creating/removing cells. For creation I use [this](https://github.com/benlubas/.dotfiles/blob/1fd059afc9d245424c726b2f6ce7a7889a524a86/nvim/lua/snippets/quarto.lua#L15) snippet.

For deletion, I would use a treesitter text object to delete the text, and `:MoltenDelete` to remove the extmark and any output. You could combine these two into a single keymap, just make sure to use `:MoltenDelete` first.

**Comment by serhez** [comment]
Thanks for answering! For the way I use notebooks, it is a bit cumbersome to have to visually select code for each cell I want to run every time I open the notebook in my editor. In other editors, such as VSCode or the native jupyter GUI, cells are already defined, so I just need to hit "SHIFT+ENTER" or click on the run button to run them when I open the file. With this plugin, I have to manually define each cell before I start working (or at least this is the best workflow I've found so far).

**Comment by benlubas** [comment]
Definitely checkout quarto-nvim linked above. I wrote its code runner parts, and it integrates with molten, and should work the way you want

**Comment by serhez** [comment]
@benlubas I just found the commands they defined; exactly what I wanted, thansk! :)
