### ISSUE TITLE
[Bug] MoltenEvaluateRange fails if end_line is past the end of the buffer

### ISSUE THREAD

**Issue by TillerBurr** [benlubas/molten-nvim#78]
- OS:Ubuntu
- NeoVim Version:0.9.4

## Description
This was discovered by @GCBallesteros in the https://github.com/GCBallesteros/NotebookNavigator.nvim/pull/25.
While trying to use the runner, if the `end_line` argument is past the buffer, it gets an "Invalid 'line': out of range" error

## Reproduction Steps
The following are the only contents of the notebook:

```python
#%%
print('hello')
```

Config (lazy.nvim):
```lua
{
	"benlubas/molten.nvim",
	version = "^1.0.0",
	build = ":UpdateRemotePlugins",
	init = function()
		vim.keymap.set("n","<leader>mt",":lua vim.fn.MoltenEvaluateRange(1,4)<CR>")
	end,
}
```

After running `:MoltenInit`, you can run the above command and you will receive the following error:

![image](https://github.com/benlubas/molten-nvim/assets/49296311/31116c18-8ae6-4a3c-a9eb-e87e914dd483)

## Expected Behavior
The cell executes without erroring. Not sure how to implement, possibly a check if `end_line` is after the end of the current buffer and use the last line of the buffer instead of the passed argument.

**Comment by benlubas** [comment]
I'll add a bounds check, and clamp the value to be between 0 and the length of the buffer. But currently in final exam crunch mode, so this will have to wait until Thursday
