### ISSUE TITLE
[Bug]  Output window off by one with tabline

### ISSUE THREAD

**Issue by GCBallesteros** [benlubas/molten-nvim#79]
- OS: macOS Ventura 13.0
- NeoVim Version: 0.9.2

## Description
The position of the output window is off by one.

![image](https://github.com/benlubas/molten-nvim/assets/6859287/c4a13a6e-3d8f-4c97-a9c3-25f9b175ad74)

The Molten cell on the image above does not cover the last `#` before the output window.

## Reproduction Steps
Run with the following config:
```lua
return {
  "benlubas/molten-nvim",
  build = ":UpdateRemotePlugins",
  init = function()
    -- this ended up not mattering  
	-- vim.g.molten_virt_lines_off_by_1 = false
  end,
}
```
- Create a new tab `:tabnew`
- run a chunk of code
- observe output window shows up 1 line too low

## Expected Behavior
Output window should be immediately below the last of the cell ~~when `g:molten_virt_lines_off_by_1=false` and should cover the last line when the latter is set to true.~~ even when there is a tabline present.

**Comment by benlubas** [comment]
@GCBallesteros do you perhaps have a tab line? or some other type of topline? I don't see this issue occurring normally for me.

I suspected that this was a tabline issue and just tested it out. It's the only way I see the behavior that you're experiencing

![image](https://github.com/benlubas/molten-nvim/assets/56943754/351abe3e-f71b-46a1-aa70-b2900d6a8bf6)

**Comment by GCBallesteros** [comment]
I do in fact have a tabline. Powered by lualine and disabling it moves the window to the expected position! I don't know enough about tabline implementations to tell who is at fault here, lualine or molten.

**Comment by benlubas** [comment]
Definitely molten, I'll look at this more on Thursday

**Comment by GCBallesteros** [comment]
No hurry. Thanks for everything
