### ISSUE TITLE
[Bug] g:molten_virt_lines_off_by_1 doesn't take effect

### ISSUE THREAD

**Issue by GCBallesteros** [benlubas/molten-nvim#80]
- OS: macOS Ventura 13.0
- NeoVim Version: 0.9.2

## Description
Changing the value of `g:molten_virt_lines_off_by_1 has no impact over the window positioning.

## Reproduction Steps
Switching between the two following configurations has no impact on how the output window is displayed.

```lua
return {
  "benlubas/molten-nvim",
  build = ":UpdateRemotePlugins",
  init = function()
      vim.g.molten_virt_lines_off_by_1 = true
  end,
}
```
```lua
return {
  "benlubas/molten-nvim",
  build = ":UpdateRemotePlugins",
  init = function()
      vim.g.molten_virt_lines_off_by_1 = false
  end,
}
```

## Expected Behavior
When said parameter is true the output window should move one line up to cover the last line of the buffer.

**Comment by benlubas** [comment]
This option only takes effect when `molten_output_virt_lines` is true. Though I suspect it still won't quite behave the way you expect b/c of #79, but we can come back to this if the issue persists after #79 is resolved
