### ISSUE TITLE
[Bug] #82 messed up window positioning

### ISSUE THREAD

**Issue by benlubas** [benlubas/molten-nvim#88]
## Description
When there are virtual lines on the top of the screen they're not accounted for properly.

![image](https://github.com/benlubas/molten-nvim/assets/56943754/401fbb05-a18b-44f6-8eb0-6a1231da0a08)

The cell ends two lines lower.

**Comment by bonryu** [comment]
Thank you for the great plugin.
I'm having an issue with the positioning of plots using matplotlib.pyplot.show(), and I'm wondering if it's related to the current issue (#82) or issue #52. 
My system info are the following:

- OS: Ubuntu 23.10
- neovim version: 0.10.0
- molten version: main branch commit [ab9351b](https://github.com/benlubas/molten-nvim/commit/ab9351baff839c2ea4b0c1b5d1ad8d4968c7f1c1) 
- image.nvim version: 1.3.0

I'm using lazyvim version 11.4.0, which uses lualine and bufferline( not tagline ), but disabling lualine and bufferline does not have an effect.

Here are three examples of improper positioning:
![Pasted image](https://github.com/benlubas/molten-nvim/assets/23230278/426097e8-8973-4d70-af9b-45551e35b83d)
![image](https://github.com/benlubas/molten-nvim/assets/23230278/1c0f8017-a307-4b11-91b7-7172d48fa282)
![image](https://github.com/benlubas/molten-nvim/assets/23230278/636b7baa-079e-4f62-b1fa-1cf1c5bb61f0)

Finally, here is an example of good positioning:
![image](https://github.com/benlubas/molten-nvim/assets/23230278/ff2f5aed-3b46-4808-8359-8a7f22cc77b2)

**Comment by bonryu** [comment]
By there way, here are my molten-nvim and image-nvim settings:
![image](https://github.com/benlubas/molten-nvim/assets/23230278/be184d03-f2d2-4aa0-a63d-bede4ad30860)
![image](https://github.com/benlubas/molten-nvim/assets/23230278/22e0e263-8e44-435e-8f9c-6474337ec594)
