### ISSUE TITLE
[Bug] nbformat needed to install

### ISSUE THREAD

**Issue by JohnEdChristensen** [benlubas/molten-nvim#97]
- OS: arch
- NeoVim Version: v0.9.4

## Description
Went thought the venv guide https://github.com/benlubas/molten-nvim/blob/main/docs/Virtual-Environments.md, but wasn't able to use any molten commands afterwords. Manually running `:UpdateRemotePlugins` showed an error coming from missing the `nbformat` package. Installing that package in my base venv resolved the issue.

## Reproduction Steps
Follow venv guide on a fresh install.

## Expected Behavior
Working install after following guide.

**Comment by benlubas** [comment]
@JohnEdChristensen Thank you for pointing that out!
